### ISSUE TITLE
ImageResizer err - Can't retrieve the file from the path: rct-image-store://0

### ISSUE THREAD

**Issue by ms88privat** [bamlab/react-native-image-resizer#1]
When I crop the image with the default native module "ImageEditingManager.cropImage" the resulting image has a path of "rct-image-store://xxx". This path can not be resized with this library. Any chance you could change this behaviour?

Thanks a lot.

edit: would be perfect if we could specify the output too e.g. `fileUri` or `base64 data` after resize

**Comment by 4ian** [comment]
Sorry for the late reply, I wasn't aware of the existence of such paths in fact :) 
Currently, `assets-library` scheme is explictly supported (see https://github.com/bamlab/react-native-image-resizer/blob/master/RNImageResizer/ImageResizerModule.m#L43), maybe you could look here if you want to try to implement support for `rct-image-store`?

**Comment by ms88privat** [comment]
@4ian Thanks for the reply. Unfortunately, I can not write Objective-C code yet. But maybe I start learning it now. I will have a look at it.

**Comment by ms88privat** [comment]
@4ian I'm not able to find the time to learn obj-c. But I think this reference might help:
https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageEditingManager.m#L54

This method can read my Image and this ImageManager is default in React-Native. There is also a method to scale the Image, but I tried this one and it does convert my image to png and make it even bigger as it was before...

But maybe you can put the pieces together :+1:

**Comment by 4ian** [comment]
Using the image loader used by React Native would make a lot of sense indeed. I'll see if I can refactor the module to use it instead of manually loading the image. Will let you know here if I make any update on this part :)

**Comment by Almouro** [comment]
Hi, this was fixed by #4 :)
