### ISSUE TITLE
Image Quality After Resize

### ISSUE THREAD

**Issue by brunolemos** [bamlab/react-native-image-resizer#104]
The quality is OK but clearly reduced, specially the color and contrast, please open the links:

| [Original](http://dreamicus.com/data/eye/eye-02.jpg) | [Resized](https://minder-photos.s3.amazonaws.com/a25828fd-8d23-4ccc-8327-07d0627c7471.jpg) |
| - | - |
| <img src="http://dreamicus.com/data/eye/eye-02.jpg" width="300" /> | <img src="https://minder-photos.s3.amazonaws.com/a25828fd-8d23-4ccc-8327-07d0627c7471.jpg" width="300" /> | 

Any way to improve that?
I see similar outputs when using https://github.com/ivpusic/react-native-image-crop-picker

`ImageResizer.createResizedImage(uri, 1000, 1000, 'JPEG', 100, 0)`

**Comment by ZainaliSyed** [comment]
I believe I had a Same Issue . Image Quality Become Poorer @4ian

**Comment by anoopmm** [comment]
Same issue here. When i rotates an image multiple times quality become poorer @brunolemos

**Comment by anoopmm** [comment]
No i am using jpeg

**Comment by 4ian** [comment]
Yes I understand, but is the same quality problem happening when you try with `PNG`? Please use PNG, do the rotation of the image multiple times and let me know if there is the same issue :)
I try to undersand if the problem comes from the image format.

**Comment by ZainaliSyed** [comment]
@wincod75  If you are using **react-native-image-picker** , you need to change **quality** prop to 1.

**Comment by wincod75** [comment]
@ZainaliSyed It's set to default to 1.0, doubt that's the issue. Testing on emulator and device, placeholder image is high res, anything uploaded through the resizer/picker gets fuzzy.

**Comment by aMarCruz** [comment]
It is the expected behavior, JPEG is a lossy format, so multiple mutations involve degradations.

**Comment by qqdayan** [comment]
@wincod75  Did you solve this problem?
