### ISSUE TITLE
Build issue with RN 0.48: compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by davidfeldt** [bamlab/react-native-image-resizer#105]
:react-native-image-resizer:compileReleaseJavaWithJavac
:react-native-image-resizer:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/david/Apps/JazLife/node_modules/react-native-image-resizer/android/src/main/java/fr/bamlab/rnimageresizer/ImageResizerPackage.java:36: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-image-resizer:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

**Comment by davidfeldt** [comment]
Here's the debug log:

08:02:23.523 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
08:02:24.307 [ERROR] [system.err] /Users/david/Apps/JazLife/node_modules/react-native-image-resizer/android/src/main/java/fr/bamlab/rnimageresizer/ImageResizerPackage.java:36: error: method does not override or implement a method from a supertype
08:02:24.308 [ERROR] [system.err]     @Override
08:02:24.308 [ERROR] [system.err]     ^
08:02:24.364 [ERROR] [system.err] 1 error
08:02:24.366 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':react-native-image-resizer:compileReleaseJavaWithJavac'
08:02:24.366 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :react-native-image-resizer:compileReleaseJavaWithJavac FAILED
08:02:24.366 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :react-native-image-resizer:compileReleaseJavaWithJavac (Thread[main,5,main]) completed. Took 0.893 secs.
08:02:24.367 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 2.374 secs, idle: 0.015 secs
08:02:24.376 [ERROR] [org.gradle.BuildExceptionReporter] 
08:02:24.376 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
08:02:24.376 [ERROR] [org.gradle.BuildExceptionReporter] 
08:02:24.376 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
08:02:24.376 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':react-native-image-resizer:compileReleaseJavaWithJavac'.
08:02:24.376 [ERROR] [org.gradle.BuildExceptionReporter] > Compilation failed; see the compiler error output for details.
08:02:24.376 [ERROR] [org.gradle.BuildExceptionReporter] 
08:02:24.376 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
08:02:24.376 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
08:02:24.377 [LIFECYCLE] [org.gradle.BuildResultLogger] 
08:02:24.377 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
08:02:24.377 [LIFECYCLE] [org.gradle.BuildResultLogger] 
08:02:24.377 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 19.384 secs
08:02:24.552 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache fileSnapshots.bin (/Users/david/Apps/JazLife/android/.gradle/2.14.1/taskArtifacts/fileSnapshots.bin)
08:02:24.553 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache fileHashes.bin (/Users/david/Apps/JazLife/android/.gradle/2.14.1/taskArtifacts/fileHashes.bin)
08:02:24.553 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache taskArtifacts.bin (/Users/david/Apps/JazLife/android/.gradle/2.14.1/taskArtifacts/taskArtifacts.bin)
08:02:24.553 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on task history cache (/Users/david/Apps/JazLife/android/.gradle/2.14.1/taskArtifacts).
08:02:24.556 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache jar snapshots cache (/Users/david/.gradle/caches/2.14.1/jarSnapshots) was closed 0 times.
08:02:24.556 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache class analysis cache (/Users/david/.gradle/caches/2.14.1/classAnalysis) was closed 0 times.
08:02:24.557 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 248, cache instances: 8, modules served from cache: 4100, artifacts: 981
08:02:24.557 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (/Users/david/.gradle/caches/2.14.1/generated-gradle-jars) was closed 0 times.
08:02:24.557 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-artifacts.bin (/Users/david/.gradle/caches/modules-2/metadata-2.16/module-artifacts.bin)
08:02:24.557 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-versions.bin (/Users/david/.gradle/caches/modules-2/metadata-2.16/module-versions.bin)
08:02:24.557 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/Users/david/.gradle/caches/modules-2/metadata-2.16/module-metadata.bin)
08:02:24.557 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/Users/david/.gradle/caches/modules-2/metadata-2.16/artifact-at-repository.bin)
08:02:24.558 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/Users/david/.gradle/caches/modules-2).
08:02:24.562 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
08:02:24.565 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 34 (avg: 0.001 secs, total: 0.034 secs)
08:02:24.565 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.007 secs
08:02:24.565 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/Users/david/.gradle/caches/2.14.1/plugin-resolution) was closed 0 times.
08:02:24.565 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopping 0 compiler daemon(s).
08:02:24.566 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopped 0 compiler daemon(s).

**Comment by 4ian** [comment]
Which version of react-native-image-resizer are you using? You should be using version 1.0.0 for React Native 0.47+ :)

**Comment by davidfeldt** [comment]
I believe its version 1.1.0? I will doublecheck.

On Sep 17, 2017, at 9:53 AM, Florian Rival <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version of react-native-image-resizer are you using? You should be using version 1.0.0 for React Native 0.47+ :)

**Comment by 4ian** [comment]
Version 1.1.0 does not exist (yet!), beware of the confusion between 1.0.0 and 0.1.1 ;)

**Comment by davidfeldt** [comment]
Yes, you are correct.  We have 0.1.1- Just updated to 1.0.0 and build was successful on Android.

**Comment by 4ian** [comment]
Sweet! Don't forget that there is a small change in the response after the resizing is done, be sure to adapt your code if needed: https://github.com/bamlab/react-native-image-resizer/commit/15ea06d7651faf316b946170427efa90ea48dc4e :)

**Comment by davidfeldt** [comment]
:)

Sent from my iPhone

On Sep 17, 2017, at 3:12 PM, Florian Rival <notifications@github.com<mailto:notifications@github.com>> wrote:


Sweet! Don't forget that there is a small change in the response after the resizing is done, be sure to adapt your code if needed: 15ea06d<https://github.com/bamlab/react-native-image-resizer/commit/15ea06d7651faf316b946170427efa90ea48dc4e> :)
