### ISSUE TITLE
Loading image at size {3000, 2002}, which is larger than the screen size {750, 1334}

### ISSUE THREAD

**Issue by brkrtp** [bamlab/react-native-image-resizer#106]
Not resize image, log: (default ios gallery images)
`[PERF ASSETS] Loading image at size {3000, 2002}, which is larger than the screen size {750, 1334}`

All images not resized... - IOS Emulator

**Comment by 4ian** [comment]
This is not a log line coming from the module. Could you paste the full code you're using and the full log content?

**Comment by brkrtp** [comment]
Okey its working my fault .

**Comment by iameyal** [comment]
@brkrtp  what was the solution?

**Comment by narek11** [comment]
What was the solution? @brkrtp

**Comment by 4ian** [comment]
Not sure what the solution was, bu the log message is not related to this issue. It's a generic message displayed by React Native when showing on screen an image that is larger than the screen size.

**Comment by Justin9606** [comment]
> It's just a warning, don't care.

i am having the same issue but seems it is effecting my tab bar switch. Is there any solution?

**Comment by Justin9606** [comment]
> Okey its working my fault .

what was the solution?

**Comment by trajano** [comment]
> > It's just a warning, don't care.
> 
> i am having the same issue but seems it is effecting my tab bar switch. Is there any solution?

In my case I am getting a slightly different dimension but I can't find any image in the directory with those dimensions.  So I'm kind of confused about it.

> [PERF ASSETS] Loading image at size {2048, 2048}, which is larger than the screen size {750, 1334}
