### ISSUE TITLE
Ios 11 new HEIC image format. Error 'Only JPEG and PNG format are supported by createResizedImage'

### ISSUE THREAD

**Issue by antakov** [bamlab/react-native-image-resizer#108]
Hi. There is an error caused by new Apple image format.

![5ba6170fda](https://user-images.githubusercontent.com/11060296/31217368-6c084dd2-a9bf-11e7-99ea-aaf721d9d6d1.jpg)

**Comment by Cygnus2112** [comment]
I got this too.

**Comment by srameshr** [comment]
Yup me too!

**Comment by bang88** [comment]
Ping @4ian Any solutions for this issues please.

**Comment by srshah19** [comment]
Any updates on this? @pfeiffer suggestion does not seem to work.

**Comment by EduardJS** [comment]
Any solutions ? I'm trying to upload images ... but .. they are HEIC format .. so I figured I could use a resizer, but then ... I get this error when trying to resize in order to convert from HEIC to JPG.

**Comment by bang88** [comment]
@EduardJS I treat them as JPEG and no errors at the moment
```
export enum SupportedFileTypes {
	'PNG' = 'PNG',
	'JPEG' = 'JPEG',
	/**
	 * IOS 11 image format
	 */
	'HEIC' = 'JPEG',
	'JPG' = 'JPEG',
}
```

**Comment by EduardJS** [comment]
@bang88 Could you elaborate your code ? I can see this is TS, and there's only one .ts file in the project, but how exactly are you using it ?
Thanks

**Comment by bang88** [comment]
@EduardJS sorry for make confusing. I mean you can check the file extension if it is `HEIC` format. you can treat it as an jpeg file.

**Comment by EduardJS** [comment]
Ah, understood :) Will give it a try now

**Comment by bang88** [comment]
It should work. hah.

**Comment by HugoGresse** [comment]
keeMeta option does NOT work on HEIC threated as jpeg :/

**Comment by baiross** [comment]
> keeMeta option does NOT work on HEIC threated as jpeg :/

up, how did you fix this issue?

**Comment by HugoGresse** [comment]
I did not :/

**Comment by socialcode-rob1** [comment]
One option is to use a HEIC converter prior to resizing.  

```javascript
if (response.filename && response.filename.endsWith('HEIC')) {
    RNHeicConverter.convert({path: response.sourceURL}).then((converted) => {
      // ... image resizer logic
    });
} else if (response.mime.match(/image\/jpeg|image\/png/)) {
   // ... image resizer logic
}
```

Library used in example: react-native-heic-converter
