### ISSUE TITLE
Async interface (Promise) but sync processing (resize impacts UI thread)

### ISSUE THREAD

**Issue by zupodaniel** [bamlab/react-native-image-resizer#112]
Hi, I'm using this project to resize images after user choose them, but even with the Async interface on the createResizedImage method, and using InteractionManager to run after animations, my subsequent UI touches are slowing down because of the resize process in background. First touch is ok because of the InteractionManager but next actions are notably delayed while resize is running.

Are there any options or guidelines to improve my use case?

**Comment by 4ian** [comment]
What is the approximate size of the image you're resizing?

**Comment by zupodaniel** [comment]
I'm using user camera photos, my smartphone is producing images about 4000x3--- to resize into 1200x1200. The processing time is about 1s.

**Comment by zupodaniel** [comment]
@4ian Any updates about that? Performance of the plugin is really not production grade for that use case or am I doing something wrong?

**Comment by 4ian** [comment]
@zupodaniel Sorry not update about that. The processing is done entirely by native Objective-C/Java functions and I do not think there is any easy way to improve this. One thing could be to spawn a thread and do the work on it, not sure how it's handled currenly by React Native!

**Comment by cristianoccazinsp** [comment]
Have you ever got an answer? Since the image processing is entirely done in Java/Objective-C, it should very easy to offload the processing a thread that does not run on the UI. I believe react's code will run on the UI thread and prevent JS interaction until it's done.
