### ISSUE TITLE
Can't retrieve the file from the path.

### ISSUE THREAD

**Issue by nes123** [bamlab/react-native-image-resizer#117]
on iOS : can't retrieve from rct-image-store://0

any ideas how to fix that ?

**Comment by tutts** [comment]
similar issue on Android (version 1.0.0):

```
file:///data/user/0/com.tutts/cache/1511984118804.JPEG
```

attempting to use in Java:

```
Bitmap bm = BitmapFactory.decodeFile(fileLocation);
```

although it returns null.

**Comment by zSergeant** [comment]
console.log(Platform.OS == 'IOS'?result.pathName:"file://"+result.pathName);
        ImageResizer.createResizedImage(Platform.OS == 'IOS'?result.pathName:"file://"+result.pathName,200,110,"PNG",0)

"file://"+result.pathName  => file:///storage/emulated/0/saved_signature/signature.png

error:Unable to load source image from path

what happen?

**Comment by tsachit** [comment]
> on iOS : can't retrieve from rct-image-store://0
> 
> any ideas how to fix that ?

Any update on this?
