### ISSUE TITLE
React/RCTImageLoader.h file not found

### ISSUE THREAD

**Issue by waterdoo** [bamlab/react-native-image-resizer#121]
Hi thanks for building a great project.

I'm getting the following issue when building my Xcode project:
React/RCTImageLoader.h file not found

react-native-image-resizer: 1.0.0
React Native: 0.51.0
Xcode: 9.2

Has anyone else run into this header issue? I've tried manually adding "${PODS_ROOT}/React" as a header search path for the Xcode target of react-native-image-resizer but that's not working.

**Comment by waterdoo** [comment]
It was an error on my end and I was able to fix the issue. It's related to changes in the podfile that the newer versions of RN need. I added:

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

To my podfile and it's working. Closing the issue.

**Comment by jwrubel** [comment]
Running in to this exact issue, and my podfile had those changes in it already. Here's mine:
```
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # required for RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
```

Super frustrating. If I don't run `pod install` I can actually build fine, but when trying to use the code I get the error [here](https://github.com/bamlab/react-native-image-resizer/issues/87). I'm sure it's some issue with my setup; it seems like ever since I added Cocoapods to the project, no library with native components installs without an issue.

**Comment by jwrubel** [comment]
I figured it out! It turned out, I needed to have `'RCTImage'` in my subspecs for `pod 'React'`. Adding that in, then re-running pod install, fixed this for me.

**Comment by zhuhengtan** [comment]
> RCTImage

And you need to delete libRCTImageResizer.a in project->targets->Build Phases->Link Binary With Libraries.

**Comment by wpratima** [comment]
> I figured it out! It turned out, I needed to have `'RCTImage'` in my subspecs for `pod 'React'`. Adding that in, then re-running pod install, fixed this for me.

I tried adding RCTImage in my pod file and running pod install, but I am still getting this error React/RCtImageLoader.h file not found from the RCTImageResizer.m file in my project. Any solutions for this?

**Comment by henaharon** [comment]
@wpratima look at the capture I have added, it did the trick for me(today) 
RN 0.60.4 
react-native-image-resizer 1.2.1

but when I changed s.dependency 'React-Core' to s.dependency 'React-RCTImage'
then `pod install`
log is **Installing react-native-image-resizer 1.3.0**
hope that help :)
![Screen Shot 2020-10-15 at 16 37 48](https://user-images.githubusercontent.com/37577083/96137535-70674000-0f05-11eb-846b-f35b90308b06.png)

**Comment by simvirakaiml** [comment]
Thank @henaharon. Your's method really works for me. It's definitely bothering me for days.
