### ISSUE TITLE
Image details

### ISSUE THREAD

**Issue by ValarrrDohaerisss** [bamlab/react-native-image-resizer#122]
When I use Webp, I see only the size,folder name,date details of the photo. What should I do to see all the features as pictured
https://hizliresim.com/p/yukle

**Comment by 4ian** [comment]
Hi! What are the features that you are talking about? (I'm getting a 403 Forbidden when following your link)

**Comment by ValarrrDohaerisss** [comment]
For example 

Before resize: https://i.hizliresim.com/1JmLXD.png

After resize :
https://i.hizliresim.com/azJLm5.png

many features disappear in detail
