### ISSUE TITLE
React Native Link doesn't add package to build.gradle dependencies

### ISSUE THREAD

**Issue by periabyte** [bamlab/react-native-image-resizer#123]
I had problem figuring out what I missed when I tried to install this package, somehow it couldn't find the `fr.bamlab.rnimageresizer` package when compiling, and somehow the manual linking guide doesn't mention this too

```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile project(':react-native-image-resizer') // it didn't add this line
}
```

**Comment by PierreCapo** [comment]
Closing this issue since this is not needed anymore with React Native 0.60 autolinking feature
