### ISSUE TITLE
图片显示5张以上就卡顿

### ISSUE THREAD

**Issue by guoguoss** [bamlab/react-native-image-resizer#125]
安卓的图片放大滑动的时候卡顿，有点卡顿

**Comment by showtan001** [comment]
我为什么一直都是报Unable to load source image from path呢 大兄弟

**Comment by showtan001** [comment]
@guoguoss

**Comment by xihairanfeng** [comment]
我也遇到了Unable to load source image from path，请问是如何解决的？

**Comment by xihairanfeng** [comment]
@showtan001
