### ISSUE TITLE
Changes needed for gradle 3.0.1 compatibility

### ISSUE THREAD

**Issue by pacamara** [bamlab/react-native-image-resizer#126]
Some minor changes are needed for gradle 3.0.1 compatibility: in android/build.gradle:
* Remove the `buildToolsVersion`, gradle now specifies a default and the current value conflicts with that.
* Declare dependencies using `api` not `compile` per https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations

We are currently hacking these changes with a script in status.im, and would rather it is fixed upstream. Thanks!

Parent issue: https://github.com/status-im/status-react/issues/3037

**Comment by 4ian** [comment]
Thanks for opening the issue :)
Is there any change that this could break compilation of Gradle version 2.x?
It seems that `api` is only supported since Gradle 3?

**Comment by pacamara** [comment]
Yes, it turns out to be a breaking change for apps authored with `react-native init`, requiring manual changes to the generated code to fix. Please see discussion at https://github.com/react-native-community/react-native-svg/issues/581#issuecomment-359192907  A solution could be to provide a separate gradle 3 tag?
