### ISSUE TITLE
package not exists in React-Native version 0.53.0

### ISSUE THREAD

**Issue by cnakh** [bamlab/react-native-image-resizer#128]
I recently try to install this package but got error as follow:
```
Path\MainApplication.java:6: error: package fr.bamlab.rnimageresizer does not exist
import fr.bamlab.rnimageresizer.ImageResizerPackage;
                               ^
Path\android\app\src\main\java\com\xxxxx\MainApplication.java:27: error: cannot find symbol
            new ImageResizerPackage()
                ^
  symbol: class ImageResizerPackage
```

**Comment by 4ian** [comment]
Can you re-run `react-native link`?
Can you double check that your build.gradle was properly modified? Looks like `react-native link` does not properly add a line, see this other issue: https://github.com/bamlab/react-native-image-resizer/issues/123

If that's not the case, add manually `compile project(':react-native-image-resizer')`.

**Comment by cnakh** [comment]
@4ian I followed the instructions
```
npm install --save react-native-image-resizer
react-native link react-native-image-resizer
```
Here is the modified:
package.json
```"react-native-image-resizer": "^1.0.0",```
package-log.json
```"react-native-image-resizer": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/react-native-image-resizer/-/react-native-image-resizer-1.0.0.tgz",
      "integrity": "sha1-1H4UlDw3k44of71jnk23zrf9iRc="
    },```
android/settings.grandle
```include ':react-native-image-resizer'
project(':react-native-image-resizer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-resizer/android')```
MainApplicaiton.java
```import fr.bamlab.rnimageresizer.ImageResizerPackage;```
And
```            new ImageResizerPackage()
```

**Comment by cnakh** [comment]
@4ian I have no idea why need to add
`compile project(':react-native-image-resizer')`
and `cd android` then `./gradlew clean`

**Comment by MarcoPortillo** [comment]
Hello, I have the next problem:

```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.

```
I followed the installation steps as indicated but it just don't work. I also did the instructions above but it didn't work. Any help?

**Comment by 4ian** [comment]
Can you double check these manual steps: https://github.com/bamlab/react-native-image-resizer/blob/master/docs/android_manual_config.md

In particular, check that the changes to `settings.gradle` are properly made.
If it does not solve the issue, please give more information about your React Native version and the library version that you're using.

**Comment by MarcoPortillo** [comment]
Yes, I read that. Everything seems ok.

React Native version: 0.52.0
library version: 1.0.0

**Comment by divyan** [comment]
@MarcoPortillo you have to do a additional npm install, then it works :)

**Comment by francaracuel** [comment]
In addition to https://github.com/bamlab/react-native-image-resizer/issues/128#issuecomment-366936900, add next line in **android/app/build.gradle** file works for me:

```
dependencies {
  ...
  implementation project(path: ':react-native-image-resizer')
  ...
}
```

**Comment by PierreCapo** [comment]
Closed as staled issue with old version of React-Native or react-native-image-resizer.
