### ISSUE TITLE
Request: change iOS deployment target to 7.0

### ISSUE THREAD

**Issue by npomfret** [bamlab/react-native-image-resizer#13]
I believe by default react-native apps are have a deployment target of 7.0.  This project is linked to iOS 9.1:

<img width="573" alt="screen shot 2016-06-16 at 11 18 20" src="https://cloud.githubusercontent.com/assets/5489469/16113500/639f1f4a-33b4-11e6-9a85-5d304bd3a625.png">

It results in a warning at build time that I'd like not to have.

If its possible, could you change the `iOS Deployment Target` in `Build Settings` to 7.0 (or as low as the code will allow)?

**Comment by 4ian** [comment]
I've made a PR to change this. :) This looks sensible, but I'm not really sure about what this option really do? I'd like to be sure about it before merging.

**Comment by npomfret** [comment]
I'm just trying to clean up the react-native build process.  If the target is set above 7 you get a warning at build time.  If this software doesn't need any features other than those in 7 it can be safely set to 7 and the warning will go away.

**Comment by 4ian** [comment]
Ok sounds good then :)
