### ISSUE TITLE
Syntax error in src/main/java/fr/bamlab/rnimageresizer/ImageResizerPackage.java:36

### ISSUE THREAD

**Issue by nichesoftgh04** [bamlab/react-native-image-resizer#132]
override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-image-resizer:compileReleaseJavaWithJavac FAILED

**Comment by jayporta** [comment]
I've gotten that error with different third-party modules Make sure react-native-image-resizer is actually in your project. Make sure it's in the usual places: MainApplication, settings.gradle, and in your app's build.gradle file (at the bottom with the other modules in the dependencies object).

**Comment by damianbuttle** [comment]
I have the same error, it's all imported correctly.  Any ideas?

**Comment by teilala** [comment]
@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
delete @override and change public to protected , and done.
fixed
protected List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
