### ISSUE TITLE
OOM - On low Memory Device 

### ISSUE THREAD

**Issue by J3j3m** [bamlab/react-native-image-resizer#133]
Hi,

I wrote this code using this great library to reduce imageSize and quality : 
```
try {
        let uri = await ImageResizer.createResizedImage('data:image/jpeg;base64,' + originalData64, imgWidth * ratio, imgHeight * ratio, 'JPEG', imgQuality);
        return uri;
 }
 catch(err){
        ALLogger.getInstance().error("ImageReducer", err);
        return err;
 }
```
Which works well for most devices, between i'm experiencing an issue on low memory device (512MB Ram / Android 4.4) with very large Image ( around 15/16mb ). 
 Is it normal to get this error ? then should I handle this otherwise ?

**Comment by evaleirasclapps** [comment]
Hi guys, any workaround here?

**Comment by pribeh** [comment]
Any ideas here?
