### ISSUE TITLE
Cannot read property 'createResizedImage' of undefined

### ISSUE THREAD

**Issue by minhphung210** [bamlab/react-native-image-resizer#134]
Hi Guys, 
Im using react:16.0.0 and react-native: 0.50.4
I installed under the instructions and rebuilt but had problems

Here is error 
<img width="786" alt="screen shot 2018-04-07 at 11 40 42 am" src="https://user-images.githubusercontent.com/25664542/38451357-93daccde-3a58-11e8-868e-c4e63d494792.png">

and here is my code: 

 `ImagePicker.showImagePicker(response => {`
      `console.log("Response = ", response);`
    `  if (response.didCancel) {`
      `  console.log("User cancelled image picker");`
     ` } else if (response.error) {`
        `Alert.alert("ImagePicker Error: ", response.error);`
    `  } else if (response.customButton) {`
      `  console.log("User tapped custom button: ", response.customButton);`
      `} else {`
        `let source = { uri: response.uri };`
        `ImageResizer.createResizedImage(source.uri, 500, 500, "JPEG", 50)`
          `.then((response) => {`
            `console.log(response);`
          `})`
          `.catch(err => {`
           ` console.log(err);`
          `});`
     ` }`
    `});`

**Comment by StanislavSergeev** [comment]
Working find on Android, but ios not working
How can I link manually on ios?

**Comment by minhphung210** [comment]
you should follow docs : https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking
and copy this text in Header Search Path: $(SRCROOT)/../node_modules/react-native-image-resizer/ios

**Comment by MahmoudElmoghazy** [comment]
Go in ios dir and run pod install

**Comment by wd** [comment]
https://github.com/bamlab/react-native-image-resizer/issues/121

**Comment by prpateldev** [comment]
I am have same error in Android.

**Comment by minhphung210** [comment]
@prpateldev  you can try manual link follow by 
https://github.com/bamlab/react-native-image-resizer/blob/master/docs/android_manual_config.md

**Comment by AbhiShrek** [comment]
I checked the example app of the image-resizer and it looks like the API is expecting the input image uri in following format: assets-library://assets/asset.JPG?id=XXXX&ext=JPG
However, the ImagePicker response.uri is like this: file:///some/long/path/1234/jpg
you need to use the ImagePicker response.origURL to give to the image-resizer.

**Comment by PierreCapo** [comment]
Closed as staled issue with old version of React-Native or react-native-image-resizer.
