### ISSUE TITLE
Why aren't the new dimensions returned in the response?

### ISSUE THREAD

**Issue by pstanton** [bamlab/react-native-image-resizer#136]
If I set maxWidth and maxHeight, I'm leaving it up to the plugin to decide on the resultant dimensions, however these are not returned in the response so they are essentially unknown. It doesn't look like it would be hard to include these in the response object.

**Comment by StevenMasini** [comment]
Yes I am also looking for this feature. We should get the new dimensions.

**Comment by pstanton** [comment]
@StevenMasini If you patch using my PR (above) it will work in android for you. I need someone to implement the equivalent to my patch in iOS - we are willing to pay if anyone is interested.

**Comment by cristianoccazinsp** [comment]
Also looking for this :)

**Comment by PierreCapo** [comment]
Done in https://github.com/bamlab/react-native-image-resizer/pull/180
