### ISSUE TITLE
Different file size from the resized file to the uploaded file.

### ISSUE THREAD

**Issue by immortalx** [bamlab/react-native-image-resizer#138]
The original file is 11Mb so its resizing and compressing for sure.

The resized file is correctly generated in the cache directory, the response object reports the correct size of 147kb.
The uploaded file ends up with 506kb. I've tried on my local server and on s3 and the file size is the same, 506kb.

I've double checked and the file exists in the system with the correct size.

Am i doing something wrong here? Do i need to set the output path or something like that?

Thank you

**Comment by qqdayan** [comment]
@immortalx  Can you learn from your code? My image compression is a bit problematic, the original size is 6M, can only be compressed to 500kb, how do you compress to 100kb?

**Comment by immortalx** [comment]
@qqdayan i set the quality to 76, but it will also depend on maxWidth and maxHeight.

**Comment by noll-fyra** [comment]
I have the same problem. My uploaded files are 3-4 times the size of the response after resizing, regardless of whether I upload from response.uri or response.path. I'm using an iPhone X to upload, so I'm wondering if it has something to do with the new HEIF format.

**Comment by immortalx** [comment]
@4ian Are we doing something wrong here or it's some kind of incompatibility with the latest version of RN?

**Comment by qqdayan** [comment]
@immortalx thanks,Picture returned is not a kilobyte,I understand the mistake.

**Comment by MHwishes** [comment]
I have the same question.@noll-fyra . I  compress file the less than 1M ,but I upload the file is more than 1M.

**Comment by EthanDM** [comment]
I was facing the issue.

Solved it with adding `../tmp` as the `outputPath`, which seems to be a better directory for this anyway.

**Comment by rupinderjeet** [comment]
@EthanDM @immortalx Can you share some minimal sample code on how you worked arround this bug?

Did you try any alternative? @bamlab do you have any clue or suggestions regarding this?

**Comment by EthanDM** [comment]
Sure, here is a utility wrapper I made for it:

```
import RnImageResizer, { Response } from 'react-native-image-resizer'

const ImageResizer = async ({
  path,
  maxWidth = 1080,
  maxHeight = 1080,
  quality = 75,
  compressFormat = 'JPEG',
  rotation = 0,
  outputPath = '../tmp'
}: {
  path: string
  maxWidth?: number
  maxHeight?: number
  quality?: number
  compressFormat?: 'PNG' | 'JPEG' | 'WEBP'
  rotation?: number
  outputPath?: string
}) => {
  return new Promise(resolve => {
    RnImageResizer.createResizedImage(
      path,
      maxWidth,
      maxHeight,
      compressFormat,
      quality,
      rotation,
      outputPath
    ).then((res: Response) => resolve(res))
  })
}

export { ImageResizer }
```

**Comment by rupinderjeet** [comment]
Thank you.

**Comment by chris44f** [comment]
Any further progress on this? Issue still present and tried ‘../tmp’ fix didn’t work for me
