### ISSUE TITLE
Why my pictures can not be compressed?

### ISSUE THREAD

**Issue by qqdayan** [bamlab/react-native-image-resizer#139]
Why my pictures can not be compressed，my code 
![1525950614 1](https://user-images.githubusercontent.com/25841666/39867134-14ece824-5486-11e8-8f96-ebbbfbb5d6c6.png)

**Comment by temiklis** [comment]
i have some problem. You fix this?

**Comment by fcostaprojects** [comment]
@qqdayan 
Some error message ?

**Comment by ilibilibom** [comment]
same issue here ... 
+1

**Comment by ilibilibom** [comment]
@qqdayan @fcostaprojects -  I believe response holds the uri you are looking for. 
Here is my code: 
```
ImageResizer.createResizedImage(imagePath, 100, 100, 'JPEG', 5)
          .then(({uri}) => {
            setImage(uri);
          })
          .catch(err => {
            console.log(err);
          });
```
