### ISSUE TITLE
Why is there no support for IOS webp?

### ISSUE THREAD

**Issue by mark-spurgeon** [bamlab/react-native-image-resizer#141]
Hi, 
I was wondering if it would be possible to save the image as WEBP in IOS, given that there is support for it with other libraries

**Comment by creambyemute** [comment]
@the-duck I'll have a look into it in the next weeks.

**Comment by Faolain** [comment]
bump @creambyemute any updates here?

**Comment by creambyemute** [comment]
@Faolain Unfortunately not, the WebP support isn't as critical for us as I first thought.

**Comment by Bill-Niz** [comment]
@creambyemute And now ?

**Comment by huseyin39** [comment]
WebP is not supported natively on iOS.

**Comment by ahansson89** [comment]
WebP will be supported on iOS 14. Would be nice if we can add it to this library.
