### ISSUE TITLE
Crash due to out of memory on iOS

### ISSUE THREAD

**Issue by sachinB94** [bamlab/react-native-image-resizer#143]
The same thing as [#97](https://github.com/bamlab/react-native-image-resizer/issues/97), but this time for iOS.

It crashes the app sometimes when trying to compress images, throwing `Terminated due to memory issue` on iOS device. It doesn't catches the memory exception, instead, crashes the app.

I think it should catch the exception and throw it in JavaScript, so that the developer can handle the issue.

**Comment by pribeh** [comment]
Same here

**Comment by pribeh** [comment]
@sachinB94 have you figured out how to resolve these types of crashes? Like what is actually causing the terminated due to memory issue with RNIR?

**Comment by suthat** [comment]
The same issue, please help

**Comment by pribeh** [comment]
I believe this fix will resolve this issue. It has for us.

https://github.com/bamlab/react-native-image-resizer/pull/205
