### ISSUE TITLE
Cannot read property 'createResizedImage' of undefined

### ISSUE THREAD

**Issue by bhatti-waqas** [bamlab/react-native-image-resizer#144]
I am getting this error 'Cannot read property 'createResizedImage' of undefined' on ios.
Need help.

**Comment by aaronlee29** [comment]
I am recently experiencing this issue as well (previously OK). Tried reinstalling, relinking. Still having trouble.

**Comment by bhatti-waqas** [comment]
Digging in, reveals that native modules are unable to load ImageResizer

`NativeModules.ImageResizer.createResizedImage(path, width, height, format, quality, rotation, outputPath, (err, response) => {
        if (err) {
          return reject(err);
        }

        resolve(response);
      });`

here in above code 'ImageResizer' is undefined.

**Comment by bhatti-waqas** [comment]
@aaronlee29 ! I resolved the issue by manually linking the library. 
Please follow the guidelines here  [https://facebook.github.io/react-native/docs/linking-libraries-ios.html](url)

**Comment by konstantin-mohin** [comment]
https://facebook.github.io/react-native/docs/linking-libraries-ios#here-are-the-few-steps-to-link-your-libraries-that-contain-native-code
