### ISSUE TITLE
how to resize the uri and base64 data?

### ISSUE THREAD

**Issue by brilliantjc** [bamlab/react-native-image-resizer#145]
I tried to combine react-native-image-picker with 
react-native-image-resizer;
why this error? THank you!!
<img width="823" alt="screen shot 2018-06-25 at 11 16 11 am" src="https://user-images.githubusercontent.com/25623417/41867879-35e4725c-7869-11e8-9081-ad8e2220e43c.png">

<img width="331" alt="screen shot 2018-06-25 at 11 08 02 am" src="https://user-images.githubusercontent.com/25623417/41867525-308b1a14-7868-11e8-9d5f-f350d4f2b6a7.png">

**Comment by rafcontreras** [comment]
Image resizer saves to the filesystem, not to the cache.

You can user react-native-fetch-blob like:
```js
ImageResizer.createResizedImage(res.uri, 8, 6, "JPEG", 80)
  .then(response => {
		RNFetchBlob.fs
		  .readFile(response.path, "base64")
		  .then(data => {
		    this.setState({ uri: res.uri, data: data });
		    this.photoTaken();
		    this.setModalVisible(false);
		  })
		  .catch(err => {
		    console.log(err);
		  });
		})
  .catch(err => {
    console.log(err);
  });
```
