### ISSUE TITLE
can i use online uri to resize

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [bamlab/react-native-image-resizer#146]

**Comment by Eyesonly88** [comment]
Yes. Tested it on Android.

**Comment by nguyenvanphuc2203** [comment]
yup! , it woking very well :D

**Comment by Eyesonly88** [comment]
FYI for future users, sometimes it doesn't work for some reason (On Android).
So I opted to use `react-native-fetch-blob` module to download the image first, then feed it to image resizer to resize it.
