### ISSUE TITLE
java.lang.Double cannot be cast to java.lang.String  on  Android

### ISSUE THREAD

**Issue by kshtjsharma68** [bamlab/react-native-image-resizer#149]
"react": "16.2.0",
"react-native": "0.55.4",
"react-native-image-resizer": "1.0.0".
I am getting this error while trying to create a resized image by passing image in base64 string format.
e.g. createResizedImage(base64, 720, 720, "JPEG", 90).

**Comment by GuoJiKaiHehe** [comment]
me too ;

**Comment by the-vishal-kumar** [comment]
Pass image uri (e.g. data:image/jpeg;base64,/9j/4Tu6RXhpZgAAS.......), as the first parameter of createResizedImage.

```
ImageResizer.createResizedImage(imageUri, newWidth, newHeight, compressFormat, quality).then((response) => {
        console.log('response===>', response, '---response');
      }).catch((err) => {
        console.log('err===>', err, '---err');
      });
```

**Comment by GedorN** [comment]
In my case, i was forgetting of a parameter. Was 'format', if are not the case, you can check if are another one.´

I hope this could help :)
