### ISSUE TITLE
keep exif after file is resized

### ISSUE THREAD

**Issue by alainib** [bamlab/react-native-image-resizer#151]
hello
i tryed this package because i need to resize and compress image before upload but need to keep Exif inside jpg

unfortunatly they are removed.

any plan to fix this please ?
thx

**Comment by AntoineAA** [comment]
Hi,
Any news about this feature?
Thanks

**Comment by cristianoccazinsp** [comment]
I believe this is a good idea as well, but might not be that easy. Not even react native camera library keeps exif info on resize, probably for a good reason.

**Comment by HugoGresse** [comment]
See https://github.com/bamlab/react-native-image-resizer/issues/208
