### ISSUE TITLE
Is a new release planned ?

### ISSUE THREAD

**Issue by JulienMalige** [bamlab/react-native-image-resizer#154]
Last release (1.0.0) is more than one year. Some last commits are fixing the lib.

Is a new release planned?

**Comment by antoinerousseau** [comment]
ping @4ian @bamlab-bot 

I'm willing to review and merge some PRs if it can help

**Comment by 4ian** [comment]
I don't have the time anymore to maintain this. Is anyone available at BAM to review the Pull Request/release a new version/close issues that are not relevant anymore? cc @tychota @Minishlink @Almouro @marekkalnik
I would be happy to give a collaborator access to a few people that could have time to update this but I don't have admin access anymore on the repository.

**Comment by Minishlink** [comment]
@antoinerousseau Can you test the last master on your app and tell me if this works great? I'll release afterwards. Thanks :)

**Comment by WandersonAlves** [comment]
As a workaround @4ian, the README.md should say that to get the newest version, point to this repo in package.json

**Comment by Minishlink** [comment]
Sorry guys for the delay, I was lacking rights on publishing this package. It's released as `v1.0.1`.
