### ISSUE TITLE
AAPT2 aapt2-3.2.0-4818971-osx Daemon

### ISSUE THREAD

**Issue by gifary** [bamlab/react-native-image-resizer#166]
I got this error when running ./gradlew assembleRelease. How to solve this issue ? Thanks
> /Users/-/Documents/android/coffeenotes/node_modules/react-native-image-resizer/android/build/intermediates/res/compiled/release/drawable-mdpi-v4_abc_textfield_default_mtrl_alpha.9.png.flat\
          -R\
          /Users/-/Documents/android/coffeenotes/node_modules/react-native-image-resizer/android/build/intermediates/res/compiled/release/values-large-v4_values-large-v4.arsc.flat\
          -R\
          /Users/-/Documents/android/coffeenotes/node_modules/react-native-image-resizer/android/build/intermediates/res/compiled/release/drawable-xhdpi-v4_abc_textfield_search_default_mtrl_alpha.9.png.flat\

**Comment by forki** [comment]
I believe this is related to buildToolsVersion "23.0.1" in the released version. RN 58 needs newer.

I think it's already fixed in master and maybe it just needs a new package release

**Comment by forki** [comment]
confirmed. If I use `"react-native-image-resizer": "bamlab/react-native-image-resizer#master"` in package.json then it works.

**Comment by gifary** [comment]
@forki Thanks for your response. I fix this with change gradle setting
