### ISSUE TITLE
Unable to resolve path to module 'react-native-image-resizer'.eslint(import/no-unresolved)

### ISSUE THREAD

**Issue by gungdeaditya** [bamlab/react-native-image-resizer#167]
I just wondering that when I use lint, I found the error for this. Resizer works fine, unless this one, how can we fix it for lint staged ?

**Comment by cristian-milea** [comment]
i have the same problem 
<img width="710" alt="Screenshot 2019-03-13 at 11 20 16" src="https://user-images.githubusercontent.com/4988454/54267503-039a0000-4582-11e9-8458-27d5e5056df4.png">

installed with `yarn add react-native-image-resizer`
checked in package.json -> exists in dependencies as `"react-native-image-resizer": "^1.0.1"`

**Comment by andresouza** [comment]
I was having the same problem and when I checked the folder `node_modules/react-native-image-resizer`, I noticed it doesn't have the `index.js`, but `index.ios.js` and `index.android.js` instead. It would be nice to have an `index.js`... but for now, you can fix this lint problem by importing the file directly like this:
`import ImageResizer from 'react-native-image-resizer/index.android'`
or
`import ImageResizer from 'react-native-image-resizer/index.ios`

A workaround would be creating a component with an `index.js` that exports to correct `react-native-image-resizer` according to the OS.
