### ISSUE TITLE
'React/RCTBridge.h' file not found

### ISSUE THREAD

**Issue by harshq** [bamlab/react-native-image-resizer#168]
Keep getting this error when I try to build the app. Linking was successful too.

"react-native": "0.57.7",
"react-native-image-resizer": "^1.0.0",

Did anyone face a similar issue ? Thanks.

**Comment by Jinochacko** [comment]
I am also facing the same issue.

Any updates on this issue?

**Comment by WeslleyNasRocha** [comment]
Any updates on this?

**Comment by PierreCapo** [comment]
closing since https://github.com/bamlab/react-native-image-resizer/commit/ca89733b62a65acee0cea161f96b849a43799006 is now on master. Please feel free to reopen the issue if you still face it
