### ISSUE TITLE
Expose the rotate function

### ISSUE THREAD

**Issue by rollsroyc3** [bamlab/react-native-image-resizer#169]
Is it possible to expose just the rotate feature? I use this throughout my app, and as many are aware, some Android devices return an image with the wrong rotation. So I'm wanting to let my user rotate manually when editing the image. The problem is if I just call createResizedImage with quality as 100 and rotating 90, the image filesize still is cut almost in half.

Would be nice to just call ImageResizer.rotate(uri, 90) and not compress the file or lose any quality.

**Comment by anhdo9797** [comment]
same issue
