### ISSUE TITLE
Resized image not found

### ISSUE THREAD

**Issue by pavermakov** [bamlab/react-native-image-resizer#170]
I need to use this library to resize pictures taken on camera. The response uri shows that the end result is located in the same directory with the original image.

However, when I try to user rn-fetch-blob to turn the resized image into base64, i get an ENOENT error.

**Comment by Jobel91** [comment]
Try that :
`Platform.OS === "ios" ? response.path : response.uri`

When you use "RNFetchBlob.fs.readFile()" response.

**Comment by tmjordan** [comment]
uri = (Platform.OS === 'ios') ? uri.replace('file:', '') : uri;
