### ISSUE TITLE
[TypeError: null is not an object (evaluating 'ImageResizerAndroid.createResizedImage

### ISSUE THREAD

**Issue by mike-niemand** [bamlab/react-native-image-resizer#175]
Android only as my project doesn't require iOS.

I have an odd issue which I can solve:

    ImageResizer.createResizedImage('file:////storage/emulated/0/test.jpg', 2048, 1536, 'JPEG', 100, 0).then((response) => {
        console.log(response)
    }).catch((err) => {
        console.log(err)
    });

Always gives me `null is not an object (evaluating 'ImageResizerAndroid.createResizedImage`

The image is there an in that path as I can display it. Is there something obvious I'm missing?

**Comment by mike-niemand** [comment]
Apologies, link didn't work correctly as per: https://github.com/bamlab/react-native-image-resizer/issues/127

**Comment by JuanMartinH** [comment]
I have the same error.

**Comment by GilesLeRockeur** [comment]
Same here :(

**Comment by PierreCapo** [comment]
Most likely the module is not linked correctly. I guess when you do `console.log(ImageResizer)` it should returned `undefined`

**Comment by wongjiahau** [comment]
I'm also having this issue

**Comment by sandisinbi** [comment]
any solution for this?

**Comment by faz919** [comment]
Also having this issue

**Comment by danielcunhas** [comment]
Anyone with the solution?

**Comment by kyleclegg** [comment]
Also seeing this for Android after following the standard installation steps i.e. `yarn add @bam.tech/react-native-image-resizer`

**Comment by longhann** [comment]
> Also seeing this for Android after following the standard installation steps i.e. `yarn add @bam.tech/react-native-image-resizer`

@kyleclegg  Have you resolved it yet? I have the same error on android

**Comment by kyleclegg** [comment]
> @kyleclegg Have you resolved it yet? I have the same error on android

I have not. Linking seems to be broken on Android. I added a platform check for the time being, but I would love to figure this out.

**Comment by haryong** [comment]
same..

**Comment by CaioMars** [comment]
Same here, looking for another library for this.

**Comment by CaioMars** [comment]
I ran into this issue too, my problem was that I was using the wrong development client. I don't know if you are using a custom development client but if you are this might be the issue.

**Comment by Shreepadav** [comment]
Any update? I'm facing this issue in Android too

**Comment by trongkhiem89** [comment]
I already to fix by manual install
https://github.com/bamlab/react-native-image-resizer/blob/master/docs/android_manual_config.md
