### ISSUE TITLE
Error when processing image

### ISSUE THREAD

**Issue by SirCameron** [bamlab/react-native-image-resizer#176]
Hi

I'm getting the following error when processing an image:

`
Requiring module "node_modules/pretty-format/build-es5/index.js", which threw an exception: TypeError: undefined is not a function (evaluating 'Object.keys(styles)[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
04-12 16:42:11.412  9073 17174 E ReactNativeJS: undefined is not a function (evaluating '_$$_REQUIRE(_dependencyMap[2], "pretty-format")(error)')
`

pretty-format module... 

I'm using RN 0.58.0

**Comment by PierreCapo** [comment]
Hello! I don't believe this error come from `react-native-image-resizer` since we do not use `pretty-format`. You should open an issue on their repo I believe.
