### ISSUE TITLE
Unable to load source image from path in Android

### ISSUE THREAD

**Issue by zSergeant** [bamlab/react-native-image-resizer#178]
`ImageResizer.createResizedImage(Platform.OS == 'IOS'?result.pathName:"file://"+result.pathName,200,110,"PNG",0)`

"file://"+result.pathName => file:///storage/emulated/0/saved_signature/signature.png

error:Unable to load source image from path

**Comment by lelghrib** [comment]
@zSergeant did you find the solution? I'm running into the same error. thx!

**Comment by lelghrib** [comment]
Found the answer in an other issue, you have to use the base 64 of the image :
` const uri64 = await toBase64(uri);
    const image = 'data:image/jpeg;base64,' + uri64;
    ImageResizer.createResizedImage(image, newWidth, newHeight, 'JPEG', 100).then()`

**Comment by Gopalakrishnan-V** [comment]
Facing the same issue, Are you able to solve this issue? @zSergeant 
Any update on this? @PierreCapo @robertbarclay @JimTeva

**Comment by HugoGresse** [comment]
We have 8k users on Pl@ntNet app having this issue on the last 2 weeks. 
We are not using the version 3 of the library though.

**Comment by SaidKherif** [comment]
An advice which worked in my case :
try to read the file with fs.readFile(...). If readFile return an error you got your issue, your file don't exist

**Comment by ashokkumar88** [comment]
@HugoGresse Did you find any work around?
