### ISSUE TITLE
Do not block React Bridge

### ISSUE THREAD

**Issue by cristianoccazinsp** [bamlab/react-native-image-resizer#179]
Would it be easy to update both Android and IOS code to run the cropping/resizing process in a separate thread/task? This would avoid blocking the bridge, and hence, the UI.

Something similar to what react native already does with its own library: https://github.com/react-native-community/react-native-image-editor/blob/master/android/src/main/java/com/reactnativecommunity/imageeditor/ImageEditorModule.java

I might take a look at the Android portion of this myself to see if it's possible, but I have no Objective-C knowledge to do the IOS side.

Was this even tried already?

**Comment by cristianoccazinsp** [comment]
Pull request here https://github.com/bamlab/react-native-image-resizer/pull/180

Seems to work like a charm. No idea if this can be also applied for IOS since I didn't see any async task related code on the IOS version of the own react's image library.

**Comment by jakobvase** [comment]
I opened a pull request for ios for exactly this 9 months ago, #160. I checked and it should still be fairly simple to merge.

**Comment by cristianoccazinsp** [comment]
So, for Android it really seemed necessary and useful. However, I haven't seen any difference with iOS. Are you sure the iOS version even runs on the UI thread? It would seem that the callback provided when reading the image already runs somewhere else ,and thus, doesn't block the UI. Correct me if I'm wrong

**Comment by jakobvase** [comment]
Resizing images blocked the UI thread for me on ios, which is why I created the pull request. But it’s been a long time, so I don’t remember exactly what I tried.

**Comment by cristianoccazinsp** [comment]
Can't really tell right now if iOS is just way too fast or there are really no issues currently. At least on an iphone 7, resizing doesn't seen to be blocking the UI. And I'm testing with images that come from the camera and are of about 5Mb size.

**Comment by jakobvase** [comment]
Thanks for testing it. I’ll try and update my usage next time I’m looking at the app, and see whether I’m still having issues. I’ll get back to you :)

**Comment by PierreCapo** [comment]
Landed on master for both iOS and Android
