### ISSUE TITLE
Doesn't work on Android if using outputPath

### ISSUE THREAD

**Issue by KjellConnelly** [bamlab/react-native-image-resizer#182]
So after banging my head for an hour or two, I figured out the problem:

First, you only need to add file:// if you're going to use a path that doesn't start with `content://` or `file://` or is a base64 string. I am using `react-native-image-picker` to get the uri. The uri is in the format `content://`, so I don't need to modify it

Next, I had an outputPath of `MyAppFiles/`. While this works for iOS, it doesn't work for Android because the java code doesn't create a directory called `MyAppFiles` if it doesn't exist already. By removing the outputPath, I was able to resize correctly. But I still want an output path (a relative path based on the current filesystem). So I modified the java file so now it says to External Storage (ie the files stay there even if the user deletes the app). This is important to me because I have multiple apps on the App Store which interact with each others' data. You don't need to use external storage. You could use the app's data container instead. In this case, in java, you would use `context.getFilesDir()` instead of what I used: `java
import android.os.Environment;
//...
Environment.getExternalStorageDirectory()
`
And then I kept the same logic for filename creation (random filename based on current timestamp). Ideally, I'd like to query the output path and check to see if it is a directory, or a filename, but I didn't want to spend the time debugging java code as it takes forever to rebuild. So I left it.

Anyways, the code changes are in my fork if you want to copy/paste the code or install my repo instead (I changed android/build.gradle though because I use a 128gb macbook air, and didn't want to install all of the different android build tools, thus had to change some of the config).

[My Fork](https://github.com/KjellConnelly/react-native-image-picker)

**Comment by pawelsas** [comment]
Looks like it's still not possible to use outputPath. Any other solutions here?
