### ISSUE TITLE
Documentation issue: critical missing step for iOS - pod install

### ISSUE THREAD

**Issue by xaphod** [bamlab/react-native-image-resizer#183]
The docs mention `react-native link`, but on the iOS side that only updates the `Podfile`. The next step for iOS to work is `cd ios && pod install` - please add this to the README.md
thanks!

**Comment by cristianoccazinsp** [comment]
Note that with RN >= 60, linking shouldn't be needed. I've been using this with RN's 60 autolinking just fine.

**Comment by PierreCapo** [comment]
Thanks for the report, README has been updated
