### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by DanielBoening** [bamlab/react-native-image-resizer#185]
Hello,

this is an amazing library and there are a lot open pull requests that seem to enhance it even more. Its sad to see some of the pull requests beeing open more than a year. 

Is this library still maintained? Is there a chance to add a new contributor that has the right to merge pull requests?

**Comment by Shaun1** [comment]
I'm also wondering about this. Looks like the last merge was ~6 months ago.

**Comment by PierreCapo** [comment]
Hello guys! Sorry for the long response delay. The main maintainer of this repository has left the project and no one really took the lead. I will **try** to find time to maintain that project.

@DanielBoening @Shaun1 is there any PR that you would like to see merged first ? I assume RN 0.60 support should be a good start.

**Comment by Dellybro** [comment]
@PierreCapo Also image loader is deprecated

**Comment by PierreCapo** [comment]
@Dellybro fixed in https://github.com/bamlab/react-native-image-resizer/pull/198
