### ISSUE TITLE
iOs 7.0 deployment target no longer supported

### ISSUE THREAD

**Issue by wichert** [bamlab/react-native-image-resizer#187]
With a XCode 10.2 setup we can no longer use this package:

```
The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.2.99. (in target 'RCTImageResizer')
```

Can you bump the deployment target to 9.0? That will still support all iOs hardware from 2011 on, and should keep us happy for another 1.5 years or so.

**Comment by PierreCapo** [comment]
Although seems to make sense to move to target 9.0, are you sure you can no longer use this package ? The example app in the [example folder](https://github.com/bamlab/react-native-image-resizer/tree/master/example) has been tested with XCode 11 and react-native v0.61. Can you confirm you are still facing this problem ?

**Comment by wichert** [comment]
We may not be. I'm not the person normally doing our mobile builds, and I haven't heard complaints from others, so I'll close this.
