### ISSUE TITLE
Android 64 bit update 

### ISSUE THREAD

**Issue by jinishalj** [bamlab/react-native-image-resizer#189]
React native version - 0.60 
Android target file 28

Please provide support for React-native-image-resizer

**Comment by cristianoccazinsp** [comment]
What part of the code exactly is forcing android to run in 32 bits mode? 

Did you mean androidx support instead?

**Comment by jinishalj** [comment]
New android update in Android apps forcing us for the android 64 bit in the component

**Comment by cristianoccazinsp** [comment]
I'm interested on this too, can tell me what Java code is not 64 bits
compatible?

**Comment by jinishalj** [comment]
Upgrade the react native version to your desired version (RN 0.60 is required for android update)

and change the targetSDK version inside the android file same of react-native-image-resizer as android/app/build.gradle targetSDK version

TargetSDK version should be 28
i have found this one as solution but i haven't tried it on my code ,please have a try

**Comment by jinishalj** [comment]
Currently we are using the react native version 0.51.0 in our app. We need to update the android build  from 32 bit to 64 bit and react native version into 0.59.1 or higher to support the android update.

Below update/Changes required in code

1.react native version update
2.android build files (from 32 bit to 64 bit)
3.Existing components in app should support the 0.59.1 version

these are the changes required in my project for up-gradation

**Comment by cristianoccazinsp** [comment]
> Upgrade the react native version to your desired version (RN 0.60 is required for android update)
> 
> and change the targetSDK version inside the android file same of react-native-image-resizer as android/app/build.gradle targetSDK version
> 
> TargetSDK version should be 28
> i have found this one as solution but i haven't tried it on my code ,please have a try

The library already uses the targetSDK variables from your project's config, so you should be fine. I'm using this library with RN 60 without issues and without 32 bits limitations.

I suggest you review your own project's ```targetSdkVersion```, ```buildToolsVersion```, and ```compileSdkVersion``` variables.

```
apply plugin: 'com.android.library'

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 26)
    buildToolsVersion safeExtGet('buildToolsVersion', "26.0.3")

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion safeExtGet('targetSdkVersion', 26)
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    compileOnly "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"
}
```

**Comment by jinishalj** [comment]
Okay thank you ,  we will check and let you know

**Comment by sinodko** [comment]
@cristianoccazinsp is autolinking enabled for this package or I need to manually link it?

**Comment by cristianoccazinsp** [comment]
It auto links just fine, no need to link with RN 60

**Comment by jinishalj** [comment]
Okay

**Comment by PierreCapo** [comment]
Thanks for helping @cristianoccazinsp closing this issue since it's solved
