### ISSUE TITLE
How to upload image using the URI

### ISSUE THREAD

**Issue by skyride99** [bamlab/react-native-image-resizer#2]
in RN there seems to be no way to upload an image through the URI. 

Using xhr,

var xhr = new XMLHttpRequest();
    xhr.open('POST', "http://" + 'makeuroffer.s3.amazonaws.com');
    xhr.onload = () => {
      console.log('status ' + xhr.status);
    };
    var formdata = new FormData();

    this.textParams.forEach((param) => {
        formdata.append(param.name, param.value)
      }
    );
    //formdata.append('file', pic.data);// {...'.\test.jpg', name: ('first'+".jpg") });
    formdata.append('image', {..., pic.uri });
    debugger;

    xhr.send(formdata);

**Comment by duncanhsieh** [comment]
@skyride99 You can try
`
formdata.append('image', {type: "image/jpeg", name: 'image.jpg', uri: 'file://' + resizedImageUri });
`
