### ISSUE TITLE
No enum constant CompressFormat.JPG

### ISSUE THREAD

**Issue by wolfag** [bamlab/react-native-image-resizer#200]
-I encounter the error: "No enum constant android.graphics.Bitmap.CompressFormat.JPG" when I call createResizedImage on Android.
-**Here my code:**
`ImageResizer.createResizedImage(
    uri,
    640,
    480,
    'JPG',
    80,
  )
    .then(res => console.log('--res', res))
    .catch(err => console.log('--error', err));`
-**My env:**
`System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 399.98 MB / 15.53 GB
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v10.5.0/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-16 | ARM EABI v7a, android-16 | Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.60.6 => 0.60.6 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7`
Please help to fix.
Thanks

**Comment by wolfag** [comment]
My mistake: 'JPG'=>'JPEG'.
Thanks

**Comment by PierreCapo** [comment]
Cool! Actually we could implement a check to the string and throw a proper error if it's not part of the enum "JPEG" / "PNG" / ...
