### ISSUE TITLE
React/RCTImageLoader.h' file not found 

### ISSUE THREAD

**Issue by harishileaf** [bamlab/react-native-image-resizer#210]
I am getting this issues on react-native 0.65.4 and react-native-image-resizer 1.1.0 on ios please find a solution for this,

**Comment by PierreCapo** [comment]
Probably related to https://github.com/bamlab/react-native-image-resizer/issues/204 Can you check this issue first, and see if it helps you @harishileaf ?
Also can you confirm you are using react-native `0.61.4` ? Because `0.65.4` is not out yet, so I assume it's a typo.

**Comment by harishileaf** [comment]
Hi @PierreCapo 
yeah sorry the version is 0.61.4 it is a typo

**Comment by PierreCapo** [comment]
@harishileaf have you been able to solve your problem with the link I've shared above ?

**Comment by harishileaf** [comment]
@PierreCapo Its working Thanks for the update

**Comment by PierreCapo** [comment]
@harishileaf Awesome !
If possible, can you quickly comment here what you did to fix your problem ? So it can help other people having the same issue. Thanks in advance 😀

**Comment by harishileaf** [comment]
i just deleted the pods folder and podfilelock.json and then reinstalled the library and did pod install
