### ISSUE TITLE
Response -> size

### ISSUE THREAD

**Issue by AlessioCamm** [bamlab/react-native-image-resizer#212]
Hi,

In my response, I've got `size: 53573`. Is the number in bytes or kilobytes ? Thanks

**Comment by rawbeans** [comment]
It is the number of bytes.

Think about how you could answer this question yourself: Inspect the file on your device in another program, or send it to your computer and look at its size there.

**Comment by AlessioCamm** [comment]
Yes you're right, but it was impossible for me to inspect the file in another device or program, so I ask the question :)
Thank you !
