### ISSUE TITLE
If maxWidth or maxHeight is larger than image width or height, image is enlarged.

### ISSUE THREAD

**Issue by rawbeans** [bamlab/react-native-image-resizer#214]
If I pass an image of width 100 to `createResizedImage`, with maxWidth set to 1000, the resulting image will be of width 1000, not 100. If this is the intended behavior, it should be better documented, and the parameter should be renamed to width.

**Comment by 404sand808s** [comment]
Just encountered this myself. Besides the aforementioned documentation suggestions, Is there no way to just not resize the image?

**Comment by crobinson42** [comment]
#233
