### ISSUE TITLE
Undefined symbols for architecture x86_64 : "_OBJC_CLASS_$_RCTImageLoader"

### ISSUE THREAD

**Issue by AlessioCamm** [bamlab/react-native-image-resizer#216]
After a lot of tests, my app won't run on **iOS**.
I have this error :

`Undefined symbols for architecture x86_64:`
`"_OBJC_CLASS_$_RCTImageLoader", referenced from:`
`objc-class-ref in libRCTImageResizer.a(RCTImageResizer.o)`
`ld: symbol(s) not found for architecture x86_64`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I use : 
`react: 16.12.0`
`react-native: 0.60.6`

**Comment by PierreCapo** [comment]
Will be fixed in https://github.com/bamlab/react-native-image-resizer/pull/211 probably

**Comment by AlessioCamm** [comment]
Thank, but not helping me :/ do you solved this problem before ?

**Comment by PierreCapo** [comment]
> Thank, but not helping me :/ do you solved this problem before ?

Did you try the fix mentioned in the pr ?

**Comment by AlessioCamm** [comment]
> > Thank, but not helping me :/ do you solved this problem before ?
> 
> Did you try the fix mentioned in the pr ?

I also try the #204 solution, but what need I to fix in the PR ?

**Comment by PierreCapo** [comment]
closing since https://github.com/bamlab/react-native-image-resizer/commit/ca89733b62a65acee0cea161f96b849a43799006 is now on master. Please feel free to reopen the issue if you still face it

**Comment by Jalil-Irfan** [comment]
I am running the salesforce ReactNative demo using Forcereact as per the [link](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/react_native_new_project.htm) 
But I am stuck at a place where Xcode throws an error and multiple warnings 
Please find the attached image for details

![Screenshot 2021-03-18 at 9 29 50 AM](https://user-images.githubusercontent.com/6348697/111575269-03b5e180-87d4-11eb-88fe-73644f684952.png)

Error  :
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTImageLoader", referenced from:
      objc-class-ref in RNSScreenStackHeaderConfig.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing Recent Messages :
**_Undefined symbol: _OBJC_CLASS_$_RCTImageLoader_**


how to clear this error 
Its working fine in Android

My System Details :
iOS 11.2.3, 
Xcode 12.4, 
node 15.11.0, 
npm 7.5.3, 
cocoapods 1.10.1, 
forcereact 9.0.0, 
typescript 4.2.3, 
yarn 1.22.10
React-native 5.0.1-aplha.1

**Comment by wmathurin** [comment]
Did you try the workaround outlined in https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios/64139830#64139830 ?

**Comment by Jalil-Irfan** [comment]
> Did you try the workaround outlined in https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios/64139830#64139830 ?

Just now tried changing the Build Active Architecture but no luck still same issue in same file

**Comment by Jalil-Irfan** [comment]
Actually another [work around](https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-790498006)) helped me 

But I had to add-in another framework "RNCMaskedView" and added the code in pod file as below 


```
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNScreens') || pod.name.eql?('RNCMaskedView')
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end
```
