### ISSUE TITLE
Proguard rules required?

### ISSUE THREAD

**Issue by tststs** [bamlab/react-native-image-resizer#218]
It seems that with proguard enabled `generateThumbnail` always throws an error `no such file or directory`. When proguard is disabled everything works as expected.

Which rules are required here? I haven't found anything in docs.

This is in production build.

Thanks in advance

**Comment by PierreCapo** [comment]
Hello @tststs 
I haven't tested this lib with proguard enabled, so I really can't guarantee you anything about that topic. If it's not supported yet as you seem to have found, indeed it would be worth it to add it to the doc until we fix that.

**Comment by tststs** [comment]
@PierreCapo 

Sorry nothing wrong with proguard rules here. In the end it was another pavkage needing proguard rules sending the path to this library. Long story but it works perfectly fine without any rules!

Sorry for the inconvenience

**Comment by PierreCapo** [comment]
Great news!
Thanks for the follow-up @tststs
