### ISSUE TITLE
React/RCTImageURLLoader.h has not found.

### ISSUE THREAD

**Issue by dipsiiiiiiiiii** [bamlab/react-native-image-resizer#221]
Hi.

I was trying to use this library. but it threw error. 
'React/RCTImageURLLoader.h'

My RN version is 0.59

After some research, I found out that If i upgraded RN, It seems to solve this problem.

But I don't want to upgrade RN.

Is there a way to solve this problem without upgrading RN?

Thanks!

**Comment by SirCameron** [comment]
Same issue!

**Comment by PierreCapo** [comment]
Hello @dipsiiiiiiiiii @SirCameron . Thanks for the report.

Please for now, uses react-native-image-resizer v1.1.0, it should be working on older version. I'll try to release a fix when I got time

**Comment by SirCameron** [comment]
@PierreCapo thanks, I am using v1.1.0

**Comment by SirCameron** [comment]
Should we be doing any manual linking in xcode?

**Comment by SirCameron** [comment]
Also, v1.1.0 release states:
```
Use RCTImageLoader instead of the deprecated imageLoader @zusinShinpei (#198)
```

**Comment by SirCameron** [comment]
> Hello @dipsiiiiiiiiii @SirCameron . Thanks for the report.
> 
> Please for now, uses react-native-image-resizer v1.1.0, it should be working on older version. I'll try to release a fix when I got time

@PierreCapo Any update? Build is still not working.

**Comment by dipsiiiiiiiiii** [comment]
@SirCameron  I can't help it, I just upgraded to 61.5 and it's working now. Upgrading was so intense

**Comment by elektronik2k5** [comment]
Can we please document this in the readme?
