### ISSUE TITLE
<React/RCTImageURLLoader.h>. I have react-native version 60.5

### ISSUE THREAD

**Issue by rupalitomar5** [bamlab/react-native-image-resizer#222]
Please give me solution

**Comment by PierreCapo** [comment]
Hello @rupalitomar5 . Thanks for the report.

Please for now, uses `react-native-image-resizer` v1.1.0, it should be working on older version. I'll try to release a fix when I got time

**Comment by rupalitomar5** [comment]
This is also not working. Because you have add #import "RCTImageURLLoader.h"
this for your all release. this Library only exist if React-native version
is 61>.

**Comment by switch13** [comment]
Same error for iOS in RN 0.60.0
/node_modules/react-native-image-resizer/ios/RCTImageResizer/RCTImageResizer.m:13:9: fatal error: 'React/RCTImageURLLoader.h' file not found
#import <React/RCTImageURLLoader.h>

The following build commands failed:
        CompileC /Users/mymachine/myapp/ios/build/myapp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-image-resizer.build/Objects-normal/x86_64/RCTImageResizer.o /Users/mymachine/myapp/node_modules/react-native-image-resizer/ios/RCTImageResizer/RCTImageResizer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by anilios** [comment]
I am also facing same issue. Wasted 2 full day on this.

**Comment by lucienbl** [comment]
Same issue on RN `0.61.5`, using this library's version `1.1.0`. Removing this on `line 13` from the `
RCTImageResizer.m` file seems to be a temporary workaround :

```diff
- #import <React/RCTImageURLLoader.h>
```

**Comment by PierreCapo** [comment]
@lucienbl indeed it seems that this`RCTImageURLLoader` isn't used in the codebase, thanks for spotting that.

I've just published a release (1.2.1) which removes this import. Can you try it and tell me if your build is now working well ?

cc @anilios @switch13 @rupalitomar5
