### ISSUE TITLE
Lexical or preprocessor issue,Not able to add & Run in React native 0.59.9.

### ISSUE THREAD

**Issue by Biplovkumar** [bamlab/react-native-image-resizer#223]
![Screenshot 2020-02-24 at 8 22 06 AM](https://user-images.githubusercontent.com/30401136/75126224-f6b4e480-56de-11ea-9603-93520f39abe8.png)

Package.JSon :- 

  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-image-picker": "^2.3.0",
    "react-native-image-resizer": "^1.2.0"
  },

Yarn Version :- 1.19.2

I am adding this library from 2 month but not succeed, but it is working fine in react-native above 60.0

**Comment by PierreCapo** [comment]
Fixed in 1.2.1
