### ISSUE TITLE
Missing Request Token for request

### ISSUE THREAD

**Issue by fega** [bamlab/react-native-image-resizer#225]
Hello, thanks so much for this work, currently I'm having a problem where I use the resizer and then I tried to upload the image using multi-part form data.

I have tried omitting the resize step and that fix the issue:
![image_from_ios](https://user-images.githubusercontent.com/6069807/76563483-7d0a4e00-6475-11ea-8a77-aa1e041096da.png)

**Comment by EagleVee** [comment]
I'm having the same issue on IOS

**Comment by fega** [comment]
@EagleVee An Workaround is using RNFS to copy the file in another place before send it over a request. Is not an optimal solution but it does the trick.

**Comment by EagleVee** [comment]
Thank you! I’ll try that out.

**Comment by retuza** [comment]
Hi, 

Same issue on IOS but I just add keepMeta paramater to true and that fix it. 
```javascript
return await ImageResizer.createResizedImage(uri, 566, 755, "JPEG", 100, 0, null,true);
```

**Comment by andre-muller** [comment]
> Hi,
> 
> Same issue on IOS but I just add keepMeta paramater to true and that fix it.
> 
> ```js
> return await ImageResizer.createResizedImage(uri, 566, 755, "JPEG", 100, 0, null,true);
> ```

Hi,

I've tried it but still not working on IOS

**Comment by 3ace** [comment]
I've had this problem when using RN 0.63.2, but after updating my RN version to 0.63.3 it solves the problem.
