### ISSUE TITLE
[Android] ImageResizerAndroid.createResizedImage argument error 

### ISSUE THREAD

**Issue by dcworldwide** [bamlab/react-native-image-resizer#23]
When running against master and 0.0.6

![screenshot_20160725-121856](https://cloud.githubusercontent.com/assets/4898751/17088710/122db7e4-5262-11e6-9ad8-f28e77e0eb56.png)

```
ImageResizer.createResizedImage(media.url, 720, 560, "PNG", 75).then((resizedImageUri) => {

```

**Comment by yairniz** [comment]
Not sure if it's relevant but I think PNGs dont compress so you may remove the quality 75

**Comment by dcworldwide** [comment]
Thats correct. But i doubt that is the issue.

**Comment by yairniz** [comment]
You can find the connected js:
\node_modules\react-native-image-resizer\index.android.js (or index.ios.js)
and Java in:
node_modules/react-native-image-resizer/android/src/main/java/fr/bamlab/rnimageresizer/ImageResizer.java
There's a newer version 0.0.7 you could try and update

**Comment by 4ian** [comment]
Should work properly with the latest version, at least no problem for me while testing the example app! :) Closing this, please re-open the issue if there is anything wrong.
