### ISSUE TITLE
No visible @interface for 'RCTBridge' declares the selector 'moduleForName:lazilyLoadIfNecessary:'

### ISSUE THREAD

**Issue by nikitph** [bamlab/react-native-image-resizer#232]
originating in RCTImageresizer.m 

    "react-native-image-resizer": "^1.0.0",
    "react-native": "0.57.7",
complains here 

 **[[self.bridge moduleForName:@"ImageLoader" lazilyLoadIfNecessary:YES] loadImageWithURLRequest:[RCTConvert NSURLRequest:path] callback:^(NSError *error, UIImage *image) {**
            if (error) {
                callback(@[@"Can't retrieve the file from the path.", @""]);
                return;
            }

**Comment by nikitph** [comment]
i would really appreciate any help with this. I am severely blocked by this.

**Comment by PierreCapo** [comment]
Hello,
Sorry for not responding sooner.
If you have react-native 0.57.7 you probably need react-native-image-resizer version stick to 1.0.0 (hard to know exactly your version with the carret syntax)

**Comment by nikitph** [comment]
i c... so u mean just hard code 1.0.0. i will try that.

**Comment by tvpranav** [comment]
Hello,
        Could you please help me to get out from this issue.
    "react-native": "0.57.7",
     "react-native-image-resizer": "^1.2.1"

I manually linked this plugin in iOS

**Comment by PierreCapo** [comment]
Hello, can you do
`"react-native-image-resizer": "1.0.0" `
instead please and tell me if that works? For 0.57.7 you need to use an old version of the lib

**Comment by tvpranav** [comment]
@PierreCapo  Thanks for this. This worked for me.
But I am getting **Thread 2: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)** while resizing image in Xcode.

`ImageResizer.createResizedImage(uri, 500, 780, 'JPEG', 100)
        .then(response => {
          console.log('After Compress -> ' + response)
        })
        .catch(err => {
          console.log('After Compress Error -> ' + err)
        });`

**Comment by nikitph** [comment]
are u using require or import?

**Comment by nikitph** [comment]
@PierreCapo ur suggestion works. it can b closed

**Comment by PierreCapo** [comment]
Thanks for the follow-up @nikitph
