### ISSUE TITLE
Unable to resize image. Most likely due to not enough memory.

### ISSUE THREAD

**Issue by hossein-zare** [bamlab/react-native-image-resizer#235]
I'm getting this error on both the emulator and android phones.
```
Unable to resize image. Most likely due to not enough memory.
```

**Comment by hossein-zare** [comment]
For those who face this annoying error.
in `android/app/src/main/AndroidManifest.xml` add `android:largeHeap="true"` to the `application` tag.

```
<application
      ...
      android:largeHeap="true"
      ...
>
```

**Comment by PierreCapo** [comment]
Thanks for making the follow-up and posting the response @hossein-zare ❤️ . Will help people that look for the issue you had
