### ISSUE TITLE
keepMeta isnot working in RN 0.61 ?

### ISSUE THREAD

**Issue by plakak13** [bamlab/react-native-image-resizer#236]
Hi,
after I update react native from 0.55 to 0.61 Exif inside image is removed. How to fix this? 
Thx

**Comment by cristianoccazinsp** [comment]
Working fine for me with RN 0.62.2 and react-native-image-resizer 1.4.5. Can you double check your source image metadata?

**Comment by cristianoccazinsp** [comment]
A PR would be awesome!

So the issue only happens on Android, and if a base64/uri is given instead of an actual file path?

**Comment by dcssi** [comment]
Yes on the case of the image being passed as base64 my fix would not help, however the code to fix that case is in the file.
Look at the function loadBitmapFromBase64 (explains how to read and decode the base 64 image)
Now if you take the variable decodedString and wrap it in a ByteArrayInputStream, you can pass the input stream to 
ExifInterface constructor.
