### ISSUE TITLE
[iOS]loadImageWithTag is deprecated

### ISSUE THREAD

**Issue by jaggerwang** [bamlab/react-native-image-resizer#24]
Resize image succeed in ios, but there is a warning message in console. It seems to some function's name changed in new React Native version.

[RCTImageLoader loadImageWithTag:callback:] is deprecated. Instead use [RCTImageLoader loadImageWithURLRequest:callback:]

![image](https://cloud.githubusercontent.com/assets/1255011/17245835/021ada2e-55bb-11e6-9745-fcac3ed7d92b.png)

**Comment by jaggerwang** [comment]
Any body here?

**Comment by sscaff1** [comment]
Same problem here. Would be great if this could be updated.

**Comment by sscaff1** [comment]
I opened up a PR.

**Comment by 4ian** [comment]
Thanks for the PR! 😄  I was a bit reluctant to do this change to avoid breaking compatibility with oldest version of React Native.
As it seems that `loadImageWithTag` method is [really removed](https://github.com/facebook/react-native/commit/7e5de707be0d0bdfe90f908b1fc7d6de08050613#diff-905836ab11c0592e87588675db52ee8b) in the upcoming v0.33 of React Native, I guess it's safe now to do the change.
