### ISSUE TITLE
NSURLResponse allHeaderFields unrecognized selector sent to instance

### ISSUE THREAD

**Issue by samrenick** [bamlab/react-native-image-resizer#240]
After upgrading to React Native 0.62.2, app crashes when calling ImageResizer.createResizedImage. Here is a screenshot: 

![image](https://user-images.githubusercontent.com/2988413/83295971-dacd4d00-a1bd-11ea-8cff-cb7499d5e6c1.png)

Full method I am calling:
```
  resizeImage(data) {
    if (Platform.OS == 'ios') {
      var width = 448;
      var height = 240;
    } else {
      width = 300;
      height = 161;
    }
    ImageResizer.createResizedImage(
      'data:image/png;base64,' + data,
      width,
      height,
      'PNG',
      100,
    )
      .then(response => {
      console.warn(response.path)
          })
          .catch(error => console.warn(error));
      })
      .catch(error => {
       console.error(error);
      });
```
Calling it with a base64 encoded string. I upgraded to image-resizer version 1.2.2, still occurring.

**Comment by samrenick** [comment]
This was apparently caused by Flipper, bumping to version 41 like this did the trick:
def add_flipper_pods!
  version = '~> 0.41.1'
  pod 'FlipperKit', version, :configuration => 'Debug'

**Comment by PierreCapo** [comment]
Thanks for adding the response @samrenick 😀
