### ISSUE TITLE
No visible @interface for 'RCTBridge' declares the selector 'moduleForName:lazilyLoadIfNecessary:'

### ISSUE THREAD

**Issue by vjhameed** [bamlab/react-native-image-resizer#243]
I get this error everytime i install a new lib . That error only occurs for ios. It complains

 [[self.bridge moduleForName:@"ImageLoader" lazilyLoadIfNecessary:YES] loadImageWithURLRequest:[RCTConvert NSURLRequest:path] callback:^(NSError *error, UIImage *image) {
            if (error) {
                callback(@[@"Can't retrieve the file from the path.", @""]);
                return;
            }

            transformImage(image, path, callback, rotation, newSize, fullPath, format, quality, keepMeta);
        }];

**Comment by menasameh** [comment]
@vjhameed I was able to fix it by downgrading react-native-image-resizer to v 1.1.0 as I'm using RN 0.55.3

**Comment by vjhameed** [comment]
Hi

Thanks for the help. That helped.
