### ISSUE TITLE
Error resizing image: Unable to load source image from path

### ISSUE THREAD

**Issue by maheshpatil2016** [bamlab/react-native-image-resizer#245]
On Android this uri results in the above error

https://images.pexels.com/photos/68147/waterfall-thac-dray-nur-buon-me-thuot-daklak-68147.jpeg

But this works just fine

file:///storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20200708-WA0013.jpg

**Comment by PierreCapo** [comment]
Closed because #256 has been merged
