### ISSUE TITLE
Make library compatible with Catalyst? AssetsLibrary not compatible

### ISSUE THREAD

**Issue by creambyemute** [bamlab/react-native-image-resizer#247]
Hey there,

It would be great if this library would be buildable for mac os with catalyst. At the moment it fails due to `/Users/myUser/dev/react/myApp/node_modules/react-native-image-resizer/ios/RCTImageResizer/RCTImageResizer.m:18:9: AssetsLibrary is deprecated and is not available when building for Mac Catalyst. Consider migrating to Photos instead, or use `#if !TARGET_OS_MACCATALYST` to conditionally import this framework, first importing TargetConditionals.h if necessary.`

There is already a PR for react-native-image-picker which has the same error: https://github.com/react-native-community/react-native-image-picker/pull/1392

Cheers

**Comment by PierreCapo** [comment]
Hello @creambyemute thanks for the report. Indeed this is really important and must be tackled soon. I don't have that much time right now, I'd be grateful someone is willing to open a PR.

Thanks for the PR link of react-native-image-picker by the way, it helps a lot 😀

**Comment by creambyemute** [comment]
@PierreCapo I might try to tackle it in the coming days
