### ISSUE TITLE
Resized images do not preserve aspect ratio on iOS in 1.2.4

### ISSUE THREAD

**Issue by EliSadaka** [bamlab/react-native-image-resizer#249]
After updating to 1.2.4, images do not preserve their aspect ratio when resized on iOS. Instead, they are always resized to whatever maxWidth and maxHeight are set to.

**Comment by Minasokoni** [comment]
I also have this issue. Do you know which version doesnt have this issue?

**Comment by EliSadaka** [comment]
@Minasokoni The previous version (1.2.3) doesn't have this issue.

**Comment by Minasokoni** [comment]
@EliSadaka I tried with 1.2.3 and Im still having the same issue.

**Comment by EliSadaka** [comment]
@Minasokoni That version is working for me. You might have to run `npm i -E react-native-image-resizer@1.2.3` to ensure that npm forces itself to install the older version.

**Comment by PierreCapo** [comment]
@EliSadaka thanks for the report. This issue is substantial enough to cause a revert of the pr merged yesterday.
Released 1.2.5 with the reverted commit.
