### ISSUE TITLE
Memory issues in an share extensions and issues in aspects ratios.

### ISSUE THREAD

**Issue by robertbarclay** [bamlab/react-native-image-resizer#250]
I am moving this discussion into an issue thread, so it can be discussed outside a closed PR and issues, with a PR to fix to follow up on this issue. This references:

https://github.com/bamlab/react-native-image-resizer/pull/248
https://github.com/bamlab/react-native-image-resizer/issues/249

I have found the issue that i believe caused 1.2.4 to cause issues in the aspect ratio, and this site gives some good insight into what is going on: 

https://useyourloaf.com/blog/stretching-redrawing-and-positioning-with-contentmode/

Basically, in 1.2.3, by default (in the underlying method) we were passing in `CGSizeZero` and using `RCTResizeModeStretch` which is `UIViewContentModeScaleToFill`. Since the original source size was used as the destination source, in did not change the aspect ratio. so there was no issues with changing the aspect ratio, since it was the original image size that consumed the full memory uncompressed of the original image, and it was working correctly but at a huge cost of memory.

```
- (RCTImageLoaderCancellationBlock) loadImageWithURLRequest:(NSURLRequest *)imageURLRequest
                                                   callback:(RCTImageLoaderCompletionBlock)callback
{
  return [self loadImageWithURLRequest:imageURLRequest
                                  size:CGSizeZero
                                 scale:1
                               clipped:YES
                            resizeMode:RCTResizeModeStretch
                           attribution:{}
                         progressBlock:nil
                      partialLoadBlock:nil
                       completionBlock:callback];
}
```

in 1.2.4, i changed it to so that we were calling the underlying method directly with the same parameters, but passing in the size instead of of `CGSizeZero`. Now we are not specifying the original aspect aspect ratio, and depending on what was passed in from outside the library, it was using the `UIViewContentModeScaleToFill`, which would skew the aspect ratio and stretch it out to the max width and height in the dimensions passed to it. so if the passed dimensions were not to that exact aspect ratio it would be skewed.

```
RCTImageLoader *loader = [self.bridge moduleForName:@"ImageLoader" lazilyLoadIfNecessary:YES];
        NSURLRequest *request = [RCTConvert NSURLRequest:path];
        [loader loadImageWithURLRequest:request
                                   size:newSize
                                  scale:1
                                clipped:YES
                             resizeMode:RCTResizeModeStretch
                          progressBlock:nil
                       partialLoadBlock:nil
                        completionBlock:^(NSError *error, UIImage *image) {
            if (error) {
                callback(@[@"Can't retrieve the file from the path.", @""]);
                return;
            }

            transformImage(image, path, callback, rotation, newSize, fullPath, format, quality, keepMeta);
        }];
```

down in the `RCTImageUtils.m` where it loads the image, it is doing a check specifying:
 ```
if (resizeMode == UIViewContentModeScaleToFill) {
    // Decoder cannot change aspect ratio, so RCTResizeModeStretch is equivalent
    // to RCTResizeModeCover for our purposes
    resizeMode = RCTResizeModeCover;
  }
```

so if it's coming in as `RCTResizeModeStretch`, it is changing it to `RCTResizeModeCover`.  In both cases we are being set to `FILL`, rather than `FIT` thus changing our aspect ratio. since now the image is being resized and not being a `CGRectZero`. On first blush, it may just simply be that we need to use the mode `RCTResizeModeContain` in this case, which would pass down `UIViewContentModeScaleAspectFit`, but i have not yet tried it out yet.

**Comment by robertbarclay** [comment]
@EliSadaka @Minasokoni does this behavior correctly describe what you were seeing in the issues in 1.2.4?

**Comment by cristianoccazinsp** [comment]
Strange, I didn't notice any issue when upgrading.

I'm passing the same width/height values (e.g., 1920) and the aspect ratio seems to be preserved.  Which case does this affect exactly?

**Comment by EliSadaka** [comment]
@robertbarclay Yeah, that does sound like the issue I was experiencing.

**Comment by robertbarclay** [comment]
What i am proposing is reimplementing the change made in 1.4.2, since for me it fixes the memory issue in the share extension, which not fix makes it a no go, but specify the `RCTResizeModeContain`, rather than `RCTResizeModeStretch`, and also specify NO clipping, so it does not try to clip the result in the low level code, but rather returns the image as is.

```
clipped ? RCTResizeImageIfNeeded(image, size, scale, resizeMode) : image
```

so it can be handled by the transform in this module. I will have a PR up of that shortly, @EliSadaka if you have some time, it would be awesome to see if that fixes your issue?

**Comment by robertbarclay** [comment]
@EliSadaka and @Minasokoni @cristianoccazinsp i have pushed up a PR and linked it here and am interested in how it does for you guys to see if it fixes the issues. I have tested in my share extension, and it is working as i would expect with the data sent. It ideally should maintain the aspect ratio from the original to what is being request as loaded. i'm having the underlying library forgo any clipping assuming that would be handled higher if it was desired.

**Comment by EliSadaka** [comment]
I just tested the PR and it seems to have fixed the issue. The original aspect ratio is being preserved now.

**Comment by robert-narrate** [comment]
Seems to be working correctly for me as well 👍

**Comment by PierreCapo** [comment]
Closing this issue since https://github.com/bamlab/react-native-image-resizer/pull/251 has been merged. Thanks for your help guys!

**Comment by cristianoccazinsp** [comment]
Seems to be working fine for me as well.

I did notice something on iOS though, which I can't tell if is related to the update or has always been there. 

For iOS only, if you try to resize a large image in 16:9 ratio, to let's say 1920x1920, the final image ends up as 1920x1081 (instead of 1080 which is the exact pixel ratio for 16:9 and 1920).  Looks like there may be a rounding issue or something there.

**Comment by PierreCapo** [comment]
@cristianoccazinsp thanks for spotting that. At first glance, I doesn't believe this is related to this commit. I'll try to have a look and test locally between 1.2.3 and 1.2.6 if I see any difference

**Comment by cristianoccazinsp** [comment]
Pretty sure it's a rounding issue.  I guess Android rounds down and iOS is rounding up? Either way, it's not a big deal, but I would guess pixels should always be rounded down.

Doing the math, it makes sense that the above test image was rounded to 1081 since the ratio multiplication ended up being something 1080.9  (which doesn't really make sense pixel-wise).
