### ISSUE TITLE
Specific devices are not compressing

### ISSUE THREAD

**Issue by SirKadogan** [bamlab/react-native-image-resizer#254]
My application depends on clients sending pictures to our servers. It is working fine for most people, but a specific client uses Samsung J5 phones. Images are NOT being compressed there. 

Using firebase performance I measured all 'sendPhoto' requests. The median is 46kb for all clients, but on J5 phones it is 3MB.

Any ideas what it could be?

**Comment by PierreCapo** [comment]
Hello @SirKadogan 
At first glance, I don't see what would cause this issue on J5 phones only. I really think we would need to have a J5 phone, try to reproduce and debug the native code to see what's happening there. Otherwise, I really have no clue how I can help you on that one.

**Comment by SirKadogan** [comment]
Yeah, I was also thinking about getting a j5 phone myself to debug that hehe  I'll let you know if I get my hands on one

**Comment by cristianoccazinsp** [comment]
Can you share some sample code? I'm curious about this as well since we rely on images being properly resized / compressed on all phones. What's the exact issue?

**Comment by SirKadogan** [comment]
Hey guys, sorry for the late reply. Turns out the mistake was on my side. I had a threshold to compress image. Images would NOT be compressed up to 3mb and these J5 phones were hitting the sweet spot at about 2.9mb and thus would not compress. 

Funny results, since most phones would either get larger than 3mb and then compress or waaay below that we didn't even notice that before. 

In any case, the library seems to be working just fine.

**Comment by PierreCapo** [comment]
Thanks for the follow-up @SirKadogan 😀

**Comment by Jdiego06** [comment]
@SirKadogan
Hello, I'm experiencing the same problem, however i don't quite understand what is going on, could you help me a little.

Thanks.

**Comment by SirKadogan** [comment]
Hi, @Jdiego06! I would suggest opening another issue. This one has been closed and I found that the error was on my side. Make sure that you're not conditionally compressing (using an if before the compression)

**Comment by Jdiego06** [comment]
This is my code:

``` takePicture = () => {
  const MAX_IMAGE_SIZE_KB = 256;

  ImagePicker.launchCamera(imagePickerOptions, async (response) => {
    if (response.uri) {
      // Compress the image if necessary
      if (response.fileSize / 1000 > MAX_IMAGE_SIZE_KB) {
        try {
          const compressedImage = await ImageResizer.createResizedImage(
            response.uri,
            1240,
            1240,
            "JPEG",
            75,
            response.originalRotation,
            null,
            true
          );

          response.fileName = compressedImage.name;
          response.fileSize = compressedImage.size;
          response.height = compressedImage.height;
          response.width = compressedImage.width;
          response.uri = compressedImage.uri;
          response.originalRotation = compressedImage.rotation;
        } catch (error) {}
      }

      this.props.addImage(response);
    }
  });
};
```
This is my code:

When I capture an image I verify its size, and compress it if necessary, or otherwise, I keep the original image.
The code works fine on many devices, but the samsung J5 does not work

I do not understand where the error is, I would appreciate a little help
