### ISSUE TITLE
Library not found for iOS

### ISSUE THREAD

**Issue by omerwaqaskhan** [bamlab/react-native-image-resizer#257]
After running the below commands:

```
yarn add react-native-image-resizer
cd ios && pod install 
```

When I try to build the app I get this error:

**ld: warning: directory not found for option '-L-L/Users/omer/Library/Developer/Xcode/DerivedData/yelpme-fmxvkwsqrtycntaquqvghjiekszm/Build/Products/Debug-iphonesimulator/react-native-image-resizer'
ld: library not found for -lreact-native-image-resizer
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

In my pod file there was nothing related to this library, then I added manually:

`pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer/'`

and run `pod install `again, but still getting the same issue.

Is there any other step to properly integrate this library, which is missing?

**Comment by huydv92** [comment]
i also same issue with you. Im using 1.3.0 || ^1.0.0 . react : 0.60.4

**Comment by MiguelAngelVM** [comment]
I have the same problem with the version 1.4.4

**Comment by Nirodha26** [comment]
Got same error and adding following to Pod file resolved it.

pod 'react-native-image-resizer', :path => "../node_modules/react-native-image-resizer/react-native-image-resizer.podspec"
