### ISSUE TITLE
New project failed on Java app:dexDebug

### ISSUE THREAD

**Issue by yairniz** [bamlab/react-native-image-resizer#26]
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'Y:\Program Files\Java\jdk1.8.0_101\bin\java.exe'' finished with non-zero exit value 2

The project is completely new with rn 0.3

**Comment by HugoMaster** [comment]
+1

**Comment by yairniz** [comment]
Works fine with 0.0.7 and install straight through rnpm
