### ISSUE TITLE
ImageResizerAndroid.createResizedImage got 10 arguments, expected 11 

### ISSUE THREAD

**Issue by LiubovChuiko** [bamlab/react-native-image-resizer#263]
After upgrade RN to 0.63.3 app is crushed on Android

<img width="316" alt="Снимок экрана 2020-11-17 в 14 29 34" src="https://user-images.githubusercontent.com/55402409/99389117-3b248800-28df-11eb-8d95-c02fb9d797e1.png">

On iOS it's working well

**Comment by PierreCapo** [comment]
@LiubovChuiko can you give us the react-native-image-resizer version you are using as well as the code you are using ?

**Comment by LiubovChuiko** [comment]
yes, it's the latest version 1.4.0

<img width="427" alt="Снимок экрана 2020-11-17 в 15 23 56" src="https://user-images.githubusercontent.com/55402409/99393743-72e2fe00-28e6-11eb-9094-f4312512bf70.png">

<img width="927" alt="Снимок экрана 2020-11-17 в 15 25 23" src="https://user-images.githubusercontent.com/55402409/99393821-9312bd00-28e6-11eb-9850-4faf9f53c5bf.png">

**Comment by LiubovChuiko** [comment]
And my app is crushed on Android here 

resize = () => {
    const { mode, onlyScaleDown, resizeTargetSize } = this.state;

    this.setState({ resizedImage: null });

    ImageResizer.createResizedImage(this.state.image, resizeTargetSize, resizeTargetSize, 'JPEG', 100, 0, undefined, false, { mode, onlyScaleDown })
      .then(resizedImage => {
        this.setState({ resizedImage });
      })
      .catch(err => {
        console.log(err);
        return Alert.alert(
          'Unable to resize the photo',
          'Check the console for full the error message',
        );
      });
  }

I don't have Alert or error in console, only this message on my Android

<img width="316" alt="Снимок экрана 2020-11-17 в 14 29 34" src="https://user-images.githubusercontent.com/55402409/99394167-1a603080-28e7-11eb-97d8-d2a5c1362e1f.png">

**Comment by PierreCapo** [comment]
I'll try to see if I can have a look today, I keep you updated.

**Comment by NatashaDawra** [comment]
Any update on this getting similar issue.

**Comment by danieltovesson** [comment]
Same, I am getting it on both iOS and Android but on Android it says was called with 11 arguments, expected 10. Attached is the error on iOS
![Simulator Screen Shot - iPhone 8 - 2020-12-09 at 15 11 23](https://user-images.githubusercontent.com/46884274/101640622-049ae280-3a31-11eb-8b36-54c9e90fd285.png)

**Comment by mariobrubio** [comment]
Any updates on this? I got the same problem.

**Comment by PierreCapo** [comment]
Hello @mariobrubio do you have any repository/code to share about how to reproduce the bug please ?

**Comment by mariobrubio** [comment]
@PierreCapo This is the portion of code that I use for resizing the image, FYI I have been using this code for a long, suddenly it stopped working

`const processData = (data) => {
    ImageResizer.createResizedImage(data.uri, 720, 720, "JPEG", 100, 0, null)
      .then(async (response) => {
        ImageEditor.cropImage(response.uri, {
          offset: { x: moderateScale(20), y: moderateScale(100) },
          size: { width: 500, height: 500 },
        }).then(async (url) => {
            // some logic
          }
        });
      })
      .catch((err) => {
        // inspect err to get more details.
      });`

**Comment by PierreCapo** [comment]
Sadly this code is running fine on the example app, and I'm not reproducing the bug. I think I'll need a repository which reproduces the bug :/

**Comment by Wendi45** [comment]
Hey so I know it is like 7 months late and you probably already figured it out. But for anyone who landed here by google search, make sure you rebuilt your android app vs just reload 😂  It fixed my issue in the case.

**Comment by Darex1991** [comment]
For me, it was a problem with the new version. Someone added in package.json `^` before the number and we had version 1.4.5. I reverted and fixed the version as 1.3.0.
