### ISSUE TITLE
Android logging tag too long

### ISSUE THREAD

**Issue by mariuswestgaard** [bamlab/react-native-image-resizer#270]
I'm getting this error when building for android:

node_modules/react-native-image-resizer/android/src/main/java/fr/bamlab/rnimageresizer/ImageResizerModule.java:112: Error: The logging tag can be at most 23 characters, was 46 (ImageResizer::createResizedImageWithExceptions) [LongLogTag]

The line in issue:                       
Log.e("ImageResizer::createResizedImageWithExceptions", "EXIF copy failed", ignored);

Env:
"react-native": "0.63.3"
react-native-image-resizer: "^1.4.2"

It builds without any error if changing LogTag to "ImageResizer::cRIWE" or anything else less 24 characters.

**Comment by ZeroCho** [comment]
error message says to add
```
lintOptions {
    abortOnError false
}
```
to `build.gradle`

but this is definitely the thing that maintainer should fix.

**Comment by PierreCapo** [comment]
Closed because of https://github.com/bamlab/react-native-image-resizer/pull/278 being merged and released. Feel free to reopen it if you still have some issues.
