### ISSUE TITLE
Where is 1.4.2?

### ISSUE THREAD

**Issue by cristianoccazinsp** [bamlab/react-native-image-resizer#272]
I was looking to update Exifinterface android dependency to test some stuff, and looks like master is only at 1.4.1, but my package.json is at 1.4.2.

Which one is the most up-to-date branch? Thanks!

**Comment by PierreCapo** [comment]
`master` is on 1.4.2 although the package.json on `master` specifies `1.4.1`,  it was not bumped when publishing to npm

**Comment by cristianoccazinsp** [comment]
Thanks.  I have been observing corrupted EXIF info on certain Android (mostly Samsung and Chinese phones) from both this library and react-native-camera (which uses an even older Exifinterface version) , and wanted to test internally updating the library. The issue comes from adding data to the "UserComment" field, which android seems to fail to add the right encoding metadata on the first 8 bytes.

Anyways, thanks for the info! This can be closed now.
