### ISSUE TITLE
Unable to find a specification for `React-Core` depended upon by `react-native-image-resizer`

### ISSUE THREAD

**Issue by hanaechahid** [bamlab/react-native-image-resizer#281]
hi, after installing the library, and run pod install inside ios folder I get this:
```
[!] Unable to find a specification for `React-Core` depended upon by `react-native-image-resizer`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```
"react-native-image-resizer": "^1.4.3"

**Comment by mehdilamrini** [comment]
Same here

**Comment by PierreCapo** [comment]
If you edit node_modules/react-native-image-resizer/react-native-image-resizer.podspec, revert that change: https://github.com/bamlab/react-native-image-resizer/commit/6db9b475d0b6afbe5f0cee31ec0097cbd69a57e2, and run `bundle exec pod install` does it fix your problem?

**Comment by alexmolod** [comment]
@PierreCapo this fixed problem for me. Thanks :)
