### ISSUE TITLE
App crashing on take a photo option.

### ISSUE THREAD

**Issue by afanchamp** [bamlab/react-native-image-resizer#285]
I'm getting this error on firebase crashlytics. my app is crashing on few android phones but not on all phones after the image is taken app crashes. 
<img width="529" alt="Screenshot 2021-04-01 at 23 25 01" src="https://user-images.githubusercontent.com/44059218/113337762-a7110580-9341-11eb-9d04-f92358db9ef5.png">

**Comment by davidmrp** [comment]
I think that it could be related to issue: https://github.com/bamlab/react-native-image-resizer/issues/283
