### ISSUE TITLE
Compress image without resizing

### ISSUE THREAD

**Issue by varungupta85** [bamlab/react-native-image-resizer#29]
Hi, is there a way to only compress the image without resizing using this library? I was thinking if I am able to find the actual image's height and width, I can just provide while invoking the API and provide the compression properties as needed which would result in the image of same dimensions but compressed. But, I didn't find any API that I can use in React Native JS code to figure out the height and width of an image. I see that you are finding out the height and width of the image in the native code. I wanted to ask if there is a way to compress an image without resizing in the current API. If not, is it possible to add such an API? Thanks!

**Comment by Almouro** [comment]
Hi @varungupta85,

I guess you could use [Image.getSize](https://facebook.github.io/react-native/docs/image.html#getsize) from React Native :)

**Comment by varun-acintyo** [comment]
Hi @Almouro, I am trying to think when I felt this stupid last time but my memory is failing me :) Thanks for the reply. You are correct. I was able to figure out the image size using the Image.getSize API. I will close the issue. Thanks!

**Comment by varungupta85** [comment]
Hi @Almouro, I am trying to think when I felt this stupid last time but my memory is failing me :) Thanks for the reply. You are correct. I was able to figure out the image size using the Image.getSize API. I will close the issue. Thanks!
