### ISSUE TITLE
Any plans on supporting react 17 and react native 0.64.2?

### ISSUE THREAD

**Issue by vemulanishanth** [bamlab/react-native-image-resizer#291]
can this project be upgraded to support react 17?

**Comment by PierreCapo** [comment]
This library doesn't contain any React component, so as for React 17 there is no issue at all. Did you face any issue with RN 0.64.2 ?

**Comment by vemulanishanth** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: <Name of the project>@<version of the project>
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.4.0 || ^16.0.0-alpha" from react-native-image-resizer@1.4.4
npm ERR! node_modules/react-native-image-resizer
npm ERR!   react-native-image-resizer@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/nvemula_static/.npm/eresolve-report.txt for a full report.


This is the error message I received when installing the package

**Comment by vemulanishanth** [comment]
I think a small change in peer dependency from `"react": "^15.4.0 || ^16.0.0-alpha"` to `"react": "^15.4.0 || ^16.0.0-alpha ||^17"` in `package.json` should do the trick.

**Comment by PierreCapo** [comment]
I think I'll even removed this line in the package.json, it doesn't have any utility since there is already a line for react-native version. Let me fix this now

**Comment by PierreCapo** [comment]
Done @vemulanishanth , I have just published react-native-image-resizer v1.4.5 which should be compatible with RN 0.64.2. Can you confirm this new version is working so that we can close the issue ?

Thanks for the reporting the issue 🙌

**Comment by vemulanishanth** [comment]
@PierreCapo Thanks for acting on it. I can install the package without any issue.

**Comment by PierreCapo** [comment]
Great ! Have a good day @vemulanishanth and thanks again
