### ISSUE TITLE
Missing tags - changelog

### ISSUE THREAD

**Issue by cristianoccazinsp** [bamlab/react-native-image-resizer#293]
@PierreCapo are you still maintaining this library? I see there are new versions in NPM, but the tags/changelog here remain unchanged.

Please let us know what has changed between versions, even if minor :)

**Comment by PierreCapo** [comment]
@cristianoccazinsp yes still here, but you are right, I didn't take the time to make a changelog. Working on it now 👀

**Comment by PierreCapo** [comment]
Done @cristianoccazinsp ✅
