### ISSUE TITLE
error version of component 1.4.5 but it shows error '<React / RCTImageLoader.h>'

### ISSUE THREAD

**Issue by pulnec** [bamlab/react-native-image-resizer#296]
I have problem installing component in react native 0.61.5, version of component 1.4.5 but it shows error '<React / RCTImageLoader.h>' file not found. this file is into folder react-native/React/CoreModules

[See problem](https://i.ibb.co/6F6QG9m/Captura-de-Pantalla-2021-08-24-a-la-s-17-44-36.png)

**Comment by saqibdoozielabs** [comment]
@pulnec  How you solved this ?
