### ISSUE TITLE
"Operation not permitted" error on Target SDK 30 android

### ISSUE THREAD

**Issue by SohelKabir** [bamlab/react-native-image-resizer#298]
Getting "Operaton not permited" error when calling this function ` ImageResizer.createResizedImage` , Everythng works fine for android less than 11 but not working on android 11 after setting target SDK 30. Which is mandatory now for play store publication. 
code blocks given below
```
try {
      const res = await ImageResizer.createResizedImage(
        img,
        600,
        600,
        imgFormat,
        70,
        0,
        `${imageFolderName}/`,
      );
      if (res) {
        try {
          const newImgFile = `${imageFolderName}/${uid}.${imgFormat}`;
          await RNFS.moveFile(res.uri, newImgFile);
          return newImgFile;
        } catch (e) {
          log('fsUtil', e);
        }
        return null;
      }
    } catch (err) {
      log('ImagePicker', err);
    }
```

**Comment by joy-betterhalf** [comment]
Hey @SohelKabir 

Our app is being rejected by the Play store because of the new policy on using MediaStore API. Did you find any issue with this particular module while submitting the app?

**Comment by mdtechcs** [comment]
getting same error with sdk level 31
