### ISSUE TITLE
[Feature] Automatic releasing

### ISSUE THREAD

**Issue by stoffern** [bamlab/react-native-image-resizer#31]
Can you add `commitizen` and `semantic-release` for better release notes, automated NPM publish?

https://github.com/commitizen/cz-cli
https://github.com/semantic-release/semantic-release

**Comment by 4ian** [comment]
Thanks for the tips! I've started using `commitizen` :) 
For semantic-release, this looks really interesting. We don't have tests that can automatically validate that a version can be released on npm though :( But I'm keeping an eye on it!
