### ISSUE TITLE
The image is rotated when I use createResizedImage function

### ISSUE THREAD

**Issue by Aguilera4** [bamlab/react-native-image-resizer#312]
Hello, this code rotate the image in some samsung devices. The parameter rotation is 0 and I dont understand it.

![image](https://user-images.githubusercontent.com/32926040/175780464-b3b397d3-3eb2-4a7e-a6e2-e0939be70512.png)

Any solution?

**Comment by omerts** [comment]
why wat this closed?

**Comment by AfanasievN** [comment]
still exists
