### ISSUE TITLE
Throws file not found error. Eventhough the file is present.

### ISSUE THREAD

**Issue by ghost** [bamlab/react-native-image-resizer#32]
The following the path. Is there anything wrong in the path format?
"file:///data/user/0/com.anonimio/cache/c327d578-f31d-4ce9-a2e4-8f411c460d9e.jpg"

**Comment by nicolai86** [comment]
we're seeing the same error, on android only. Everything works on iOS

**Comment by developercode1** [comment]
Any solutions for this ?

**Comment by the-yadu** [comment]
<img width="656" alt="screen shot 2018-08-21 at 10 14 18 am" src="https://user-images.githubusercontent.com/7404181/44380839-38cdfa80-a52b-11e8-8a0e-a90209c7cdf6.png">
Same here net::ERR_FILE_NOT_FOUND 
GET file:///data/user/0/com.managemyrides.dev/cache/1534826310567.JPEG net::ERR_FILE_NOT_FOUND

**Comment by DISKONEKTeD** [comment]
did any of you figure this out?

**Comment by DISKONEKTeD** [comment]
how do we actually know the file is there? I'm looking through android file transfer and nothing comes up in the cache folder

**Comment by spruce-bruce** [comment]
Ah got it, in my case i was providing the file name in `outputPath`. So the file that didn't exist was the `filename.jpeg` directory.
