### ISSUE TITLE
Typo for createResizedImage

### ISSUE THREAD

**Issue by Saikedo** [bamlab/react-native-image-resizer#321]
It seems like the documentation says that we should use `ImageResizer.createResizedImage` but in version 3.0.0 it seems like there is a typo in `createResizedImage` and instead it says `createdResizedImage` (notice that it says `created` instead of `create`).

**Comment by Saikedo** [comment]
I am also getting `TypeError: undefined is not an object (evaluating 'p.default.createdResizedImage')` every time I try to use the library.

And on Android the same with a very similar message. Can this be related?

**Comment by taboulot** [comment]
Hey @Saikedo 

Indeed, I did some mistakes during the turbo module migration & I apologize.
I've already fixed the version number in the README.
Can you help me & create a PR for the other typos?

**Comment by raquelmsmith** [comment]
I'm also seeing this error. Were you able to get it working?

**Comment by taboulot** [comment]
Indeed I made a typo when I generated the method.
The doc says `createResizedImage` but index export `createdResizedImage` => going to fix it.

For the error you have can you provide me a reproducible example?
