### ISSUE TITLE
No default module and not-optional options in README

### ISSUE THREAD

**Issue by kueda** [bamlab/react-native-image-resizer#329]
As far as I can tell the [example code in the README](https://github.com/bamlab/react-native-image-resizer/#usage-example) does not work in 3.0.0 for two reasons:

1. `import ImageResizer from '@bam.tech/react-native-image-resizer';` does not return an object with a `createResizedImage` attribute. Following the example app, you need to do `import { createResizedImage } from '@bam.tech/react-native-image-resizer';`
2. The `options` argument for `createResizedImage` does not seem to be optional anymore, so the fact that the README code omits it results in a crash.

I was going to just fix the documentation, but I wasn't really sure if these were bugs or intended changes in the functionality.

**Comment by taboulot** [comment]
@kueda 

Thank you for your feedback.

For point 1, I have created this PR #330. Thank you for catching it.

For point 2, I will come back to you later with a proper response.

**Comment by taboulot** [comment]
Fixes have been deployed on version `3.0.1`.
