### ISSUE TITLE
iOS [__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

### ISSUE THREAD

**Issue by Parkjunwu** [bamlab/react-native-image-resizer#334]
Hello!

When I use "@bam.tech/react-native-image-resizer" this new version with code

" await ImageResizer.createResizedImage(uri, width, height, "JPEG", 90, 0, null, false, {onlyScaleDown:true}); "

then it is not worked with " iOS [__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0] " message.

When I use "react-native-image-resizer" package which is old version, it works well.

I use M1 air and React Native 0.70.1 version.

Thank you!

**Comment by joshnissenbaum** [comment]
Same issue. Reverted back to the old version for now

**Comment by taboulot** [comment]
Hey @Parkjunwu & @joshnissenbaum,

Thank you for reporting the issue. I have identified the problem.
I will push a fix this morning.
