### ISSUE TITLE
Error: Missing argument 'path' and/or 'destination

### ISSUE THREAD

**Issue by gararanjeet** [bamlab/react-native-image-resizer#340]
I just followed the example provided in the example section of this repo. But I m getting missing argument "path" and/or "destination".
Here is the function 

![image](https://user-images.githubusercontent.com/102017100/196256170-563c0a5f-c106-430e-b3c7-515303b214e3.png)

Here is the error log.

![image](https://user-images.githubusercontent.com/102017100/196256322-4fae29ca-6f53-4b5d-b5a4-9f4dbe50eebc.png)

Thanks In advance!!!

**Comment by taboulot** [comment]
Hi @gararanjeet,

Which version of the library are you using?
Do you have the problem on both iOS & Android?

**Comment by gararanjeet** [comment]
Hi @taboulot ,
Haven't tried it on ios.
react-native - 0.63.4
@bam.tech/react-native-image-resizer - ^3.0.3
