### ISSUE TITLE
[TypeError: Cannot read property 'createResizedImage' of null] on Android

### ISSUE THREAD

**Issue by longhann** [bamlab/react-native-image-resizer#344]
"@bam.tech/react-native-image-resizer": "3.0.4"
"react-native": "0.64.2"
"react": "16.13.1"

It's work on IOS but show this on Android (simulator API 31). `[TypeError: Cannot read property 'createResizedImage' of null] on Android`

I've tried:
- Use autolink by re-installing packages with --save `npm install (yarn) @bam.tech/react-native-image-resizer --save` => fail
- Run link command `yarn react-native link @bam.tech/react-native-image-resizer` => only link for IOS

*Updated: `yarn add react-native-image-resizer@1.1.0` and it works on Android but not in IOS at the same time as  [error](https://github.com/facebook/react-native/issues/23835) so I installed both of 2 versions

**Comment by tuan072090** [comment]
same error on android

**Comment by longhann** [comment]
> same error on android
Not the best way but you can try the solution I mentioned above

`*Updated: yarn add react-native-image-resizer@1.1.0 and it works on Android but not in IOS at the same time as https://github.com/facebook/react-native/issues/23835 so I installed both of 2 versions`

**Comment by alessandrom** [comment]
I am also facing this issue on Android only

**Comment by alessandrom** [comment]
Digging in the library I can see that `isTurboModuleEnabled` is false and  `NativeModules.ImageResizer` is undefined
```
const ImageResizer = isTurboModuleEnabled
  ? require('./NativeImageResizer').default
  : NativeModules.ImageResizer;
```

I wonder if it may depend on a specific device

**Comment by javier2409** [comment]
I'm having the same issue on Android with 3.0.4 version, iOS works fine. Downgrading to 1.4.5 worked on both OS for me.

**Comment by CaioMars** [comment]
I ran into this issue too, my problem was that I was using the wrong development client. I don't know if you are using a custom development client but if you are this might be the issue.

**Comment by taboulot** [comment]
Hi @longhann,

I was not able to reproduce it.

Did you find a solution ?
If no, can you provide me a reproducible example ? 

@CaioMars looks like you already faced the issue. You already gave this answer in #353.

Can you give me more details about what was the problem and how you fixed it ?

**Comment by mljlynch** [comment]
This is true for me as well - does this have something to do with hermes on android?
