### ISSUE TITLE
Cant install package!

### ISSUE THREAD

**Issue by abdullahIsa** [bamlab/react-native-image-resizer#355]
Hello getting this error when i try installing using NPM 

At line:1 char:13
+ npm install @bam.tech/react-native-image-resizer
The splatting operator '@' cannot be used to reference variables in an expression. '@bam' can be used only as an argument to a command. To reference variables in an expression use '$bam'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted

**Comment by AntoineDoubovetzky** [comment]
@abdullahIsa did you try `npm install "@bam.tech/react-native-image-resizer"` ?

**Comment by abdullahIsa** [comment]
> @bam.tech/react-native-image-resizer

ahaha worked, silly mistake, thanks.
