### ISSUE TITLE
resized image quality is very poor

### ISSUE THREAD

**Issue by leoabacade** [bamlab/react-native-image-resizer#37]
Nexus 6 - 5.1.1
"react": "15.2.1",
"react-native": "^0.28.0",
"name": "react-native-image-resizer",
"version": "0.0.6",

original image:

<img width="495" alt="screen shot 2016-08-23 at 5 10 53 pm" src="https://cloud.githubusercontent.com/assets/2664504/17886536/d8a81334-6954-11e6-8201-39b3a0b2a0ff.png">

resized image with 100 in quality in parameter setting:
ImageResizer.createResizedImage(uri, 100, 100, 'JPEG', 100)

![e6z9ypyv_profile_20160812104929](https://cloud.githubusercontent.com/assets/2664504/17886532/d1f1fd16-6954-11e6-8845-43d2795102d7.jpeg)

I just need to resize the image and stay on original quality, please help, thanks

**Comment by 4ian** [comment]
Hey @leoabacade. Can you try with the latest version on npm? :)

**Comment by leoabacade** [comment]
much better, thanks for this nice module

"name": "react-native-image-resizer",
"version": "0.0.8",
ImageResizer.createResizedImage(uri, 100, 100, 'JPEG', 100, 0, null)

![cpy9z72q_profile_20160823114748](https://cloud.githubusercontent.com/assets/2664504/17890824/d735b6f8-696a-11e6-9148-3606923e0619.jpeg)
