### ISSUE TITLE
uriString App crashing on Android device while taking picture In React Native In Mac

### ISSUE THREAD

**Issue by jigaradesarasa** [bamlab/react-native-image-resizer#374]
[**Describe](url) the bug**
'' uriString'' this error related to  @bam.tech/react-native-image-resizer
 My Package version is "@bam.tech/react-native-image-resizer": "^3.0.5"

**Observed behavior**
when i capture the image and select the photo for upload , then this error comes.

**Screenshots**
**Link to reproducible example**
https://.....![image](https://github.com/bamlab/react-native-image-resizer/assets/121226160/39e88d7d-88a8-4031-b5a3-003deb31d4c8)

any one have any solution ?

**Comment by taboulot** [comment]
@jigaradesarasa 

Without more information it is going difficult to help you.
How do you use this package ? 
Do you have code sample ?
