### ISSUE TITLE
[3.0.6] is missing types

### ISSUE THREAD

**Issue by efstathiosntonas** [bamlab/react-native-image-resizer#383]
After upgrading to `3.0.6` I get missing types error.

![Screenshot 2023-08-22 at 15 48 23](https://github.com/bamlab/react-native-image-resizer/assets/717975/f857e8e5-1800-4e32-bed7-6c37eae301f0)

**Comment by atheck** [comment]
Same here

**Comment by taboulot** [comment]
@efstathiosntonas & @atheck  just saw the problem 😩

For any reason the type files generation path changed...

Going to investigate why and push a fix before the end of the day.

Until then the patch you can apply:
```
// Go in node_modules/@bam.tech/react-native-image-resizer/package.json

// Replace this line
 "types": "lib/typescript/src/index.d.ts",

// by this line
 "types": "lib/typescript/index.d.ts",
```

Sorry for that.

**Comment by atheck** [comment]
No problem. Thank you for your effort.

**Comment by taboulot** [comment]
@efstathiosntonas & @atheck new release `3.0.7` published with fix.

**Comment by efstathiosntonas** [comment]
Thanks @taboulot!! Keep it up
