### ISSUE TITLE
output to base64 string

### ISSUE THREAD

**Issue by fgrs** [bamlab/react-native-image-resizer#39]
is this currently possible?

**Comment by 4ian** [comment]
Not currently, but you can use a module like [react-native-fs](https://github.com/johanneslumpe/react-native-fs) to read the output file that was created by react-native-image-resizer. See [readFile](react-native-image-resizer) method documentation.
Beware of large files, it can be quite hazardous to store such files in a base64 string.

**Comment by fgrs** [comment]
I did it the way you suggested but now for image resized and saved in

`file:/data/data/com.app/cache/1472039430399.JPEG`

I get following error in readFile:

`Error: ENOENT: no such file or directory, open 'file:/data/data/com.app/cache/1472039430399.JPEG'(…)`

**Comment by fgrs** [comment]
is this path correct? file:/data/data/com.app/cache/1472039430399.JPEG

**Comment by 4ian** [comment]
Not sure, you should double-check if the file is really on the device or not using for example the android tools in Android Studio :)

**Comment by virgial** [comment]
Maybe too late for you, but it can help others. storing local files on real devices will give dynamic document/caches directories. To find the correct app directory, us react-native-fs:
```javascript
var RNFS = require('react-native-fs');
var filepath = RNFS.DocumentDirectoryPath + '/'+yourfilename;
var readfile = RNFS.readFile(filepath, 'utf8');
```
the 'DocumentDirectoryPath' will give you your current documentpath.

**Comment by LucasMonteiro1** [comment]
Any update?

**Comment by peterholcomb** [comment]
If anyone runs into this, @virgial is mostly correct, although you need to use
```
var readfile = RNFS.readFile(filepath, 'base64')
```
instead of utf8.

https://github.com/itinance/react-native-fs/issues/417

**Comment by Kicker93** [comment]
This works: 'data:image/jpeg,'+image
The code expects a comma before the base64 image, for some reason...

**Comment by coderjoel** [comment]
@mickael-h Your solution is not suited for the question. You might be replying for 'how to upload base 64'
