### ISSUE TITLE
'cover' mode does not work as expected

### ISSUE THREAD

**Issue by ionflow** [bamlab/react-native-image-resizer#392]
**Describe the bug**
The definition of 'cover' in other contexts means the image is clipped to fit the container. In this library `cover` chooses width or height but does not respect both. In, for example, [CSS the `object-fit: cover` property clips](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) the left/right or top/bottom when the image content does not fit inside the container size. 

It would be nice if this library at least had an additional property (`crop`?) to achieve this for quick cropping to the image center. 

**To Reproduce**
1. Run the following on any image that doesn't have dimensions 768x512:
```
      ImageResizer.createResizedImage(
        media.path,
        768,
        512,
        "JPEG",
        50,
        0,
        undefined,
        false,
        {
          mode: "cover",
          onlyScaleDown: false,
        }
      )
```

**Observed behavior**
The resulting image will be either 768px wide or 512px tall but not both and will maintain the original images aspect ratio. (I understand this is the documented behavior, but it is not the standard `cover` behavior in other contexts).

**Expected behavior**
I would expect the resulting image to be exactly 768x512 with either top sides cropped equally or the top and bottom cropped equally.

**Screenshots**
<img width="345" alt="Screenshot 2024-01-20 at 11 04 48 AM" src="https://github.com/bamlab/react-native-image-resizer/assets/4053903/96254f08-b783-46fc-b1d3-1254acbc04f1">

**Platform concerned:**
 - Device: iPhone13 Pro
 - OS: iOS17.2

**Comment by jonxssc** [comment]
Same issue still today

**Comment by terminalh2t3** [comment]
Same issue
