### ISSUE TITLE
Isn't `rotatedImage != rotatedImage` always true?

### ISSUE THREAD

**Issue by retyui** [bamlab/react-native-image-resizer#394]
**Describe the bug**

Hi bam engineers. can you explain how the next line should works 

https://github.com/bamlab/react-native-image-resizer/blob/96721a2c346c3254e28bf48e81cd4ed7815d24e3/android/src/main/java/com/reactnativeimageresizer/ImageResizer.java#L560-L562

**Comment by macksal** [comment]
As an optimisation, it could be possible for rotateImage() to return the same Bitmap when rotation=0.

**Comment by 0xc22b** [comment]
Should it be rotatedImage != sourceImage?

**Comment by macksal** [comment]
ha, you're right. I wonder if there's a memory leak because of this? Not sure if Bitmap.recycle is necessary to call or if it can still be GC'd

**Comment by taboulot** [comment]
Hey !
Indeed I think it's not normal.
Will be fixed in this PR once merged : #398

**Comment by taboulot** [comment]
@retyui 

I close this issue has it must be fixed in [3.0.10](https://github.com/bamlab/react-native-image-resizer/releases/tag/v3.0.10).
