### ISSUE TITLE
Build Error > Task :bam.tech_react-native-image-resizer:buildCodegenCLI FAILED in android build.

### ISSUE THREAD

**Issue by fortesssapp** [bamlab/react-native-image-resizer#397]
**Bud Issue**
I install [@bam.tech/react-native-image-resizer] from NPM, built and ran well for iOS, but could not build and run for android.

**To Reproduce**
1. Install `npm i @bam.tech/react-native-image-resizer `from npm
2. Try to use based on the instruction from the npm page
3. Try to build and run on android device (Simulator) `npx react-native run-android`

**Observed behavior**
Build encountered error:` > Task :bam.tech_react-native-image-resizer:buildCodegenCLI FAILED`

**Expected behavior**
To run successfully as on the iOS device. 

**Screenshots**
<img width="601" alt="Screenshot 2024-03-28 at 11 58 04 PM" src="https://github.com/bamlab/react-native-image-resizer/assets/150045790/15ae2cf4-3d4c-4275-8902-0fca685296e0">

**Platform concerned:**
 - Simulator Device: [Emulator Pixel_5_API_33]
 - React-Native Version: [0.72.0]

**Comment by taboulot** [comment]
Available in `3.0.8`

**Comment by fortesssapp** [comment]
Thank you @taboulot for getting back to me. Testing right away.
