### ISSUE TITLE
Build failed with react@15.3.1 and react-native@0.32.0

### ISSUE THREAD

**Issue by jaggerwang** [bamlab/react-native-image-resizer#40]
The build error is as follow.

`/Users/jagger/projects/zaiqiuchang/app/node_modules/react-native-image-resizer/ios/RCTImageResizer/RCTImageResizer.m:53:26: No visible @interface for 'RCTImageLoader' declares the selector 'loadImageWithTag:callback:'`

![image](https://cloud.githubusercontent.com/assets/1255011/18008801/33d7bfa0-6bdc-11e6-9a81-aaadcffd997a.png)

**Comment by 4ian** [comment]
Try with the latest version from master, we merged a fix 3 days ago (https://github.com/bamlab/react-native-image-resizer/commit/8e9adf7a13d676e781e964c81c14a9d345847d9d) to get rid of this method that was deprecated and now removed in React Native 0.32 :)
I'm going to publish an updated version on npm

**Comment by 4ian** [comment]
Published version [0.0.9](https://github.com/bamlab/react-native-image-resizer/releases/tag/0.0.9) :)
Let me know if it's working for you and we can close the issue.

**Comment by jaggerwang** [comment]
It’s working now:) Thanks a lot!

**Comment by 4ian** [comment]
:v:
