### ISSUE TITLE
Still image rotation is happening- 3.0.8

### ISSUE THREAD

**Issue by Sachin1116** [bamlab/react-native-image-resizer#400]
Still image rotation is happening in some android device...I checked this in oneplus mobile

**Comment by taboulot** [comment]
Hi @Sachin1116,

We are all waiting for something...
On my side I'm waiting for a reproducible example.
Thank for sharing the model on which you have the problem.

I think it's related to this [PR](https://github.com/bamlab/react-native-image-resizer/pull/398).
You can contribute to it.

Can you add in comment with the device, the android version & RN version on which you have the issue ? Thanks.

**Comment by taboulot** [comment]
@Sachin1116 thank.
Can you share with me:
- an example of the behavior you have vs the behavior you expect ?
- the original image of your example ?

**Comment by taboulot** [comment]
@Sachin1116 

I close this issue has it must be fixed in [3.0.10](https://github.com/bamlab/react-native-image-resizer/releases/tag/v3.0.10).
