### ISSUE TITLE
[Question] How to define output file name

### ISSUE THREAD

**Issue by rossicler-hostalky** [bamlab/react-native-image-resizer#406]
Hi, how can I define the name of the output file?

I see that I can set the outputPath, but it comes with a random filename, which doesn't work as well to me. In my use case I want the resized images output path to be predictable, and for that I want to have the same name as the original image, but in a different folder.

I implemented a workaround of "renaming" the output path, but this is increases the time by almost 2x.

**Comment by alexrififi** [comment]
Good idea! Too bad it won't work at the moment
