### ISSUE TITLE
Fail to build on iOS with new react-native 0.76.1 (new architecture)

### ISSUE THREAD

**Issue by gigilibala** [bamlab/react-native-image-resizer#415]
**Describe the bug**

Fails to build on iOS with new react-native 0.76.1 which has the fabric and turbo (new architecture) with the following error:

```
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/amin/Library/Developer/Xcode/DerivedData/myapp-ayngvqncgkobtibvyulqfcmnhvgm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-image-resizer.build/Objects-normal/arm64/ImageResizer.o /Users/amin/Projects/test/new-proj/myapp/node_modules/@bam.tech/react-native-image-resizer/ios/ImageResizer.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-image-resizer' from project 'Pods')
        Building workspace myapp with scheme myapp and configuration Debug
(2 failures)
```

**To Reproduce**

```
npx react-native@latest init myapp
npm add bamlab/react-native-image-resizer

cd myapp/ios
pod install
cd ..

npx react-native run-ios

# then press i
```

run the given `xcodebuild` command which failed in previous step. It will reproduce the error above.

**Observed behavior**
See logs above.

**Expected behavior**
It needs to build iOS successfully.

**Screenshots**
See logs above.

**Platform concerned:**
 - OS: iOS 18.1 

**Additional context**
N/A

**Link to reproducible example**
N/A

**Comment by atulbhuriya** [comment]
same issue

**Comment by macksal** [comment]
I think this is a duplicate of #410 which has more details of the specific problem

**Comment by gigilibala** [comment]
Merging to https://github.com/bamlab/react-native-image-resizer/issues/410
