### ISSUE TITLE
Cannot read file with React Native FS

### ISSUE THREAD

**Issue by ChrisCates** [bamlab/react-native-image-resizer#50]
Not sure what's going on here:
Here's a sample app I am working on and am debugging.

```
'use strict';
import React, { Component } from 'react';
import {
  AppRegistry,
  Dimensions,
  StyleSheet,
  Text,
  TouchableHighlight,
  View
} from 'react-native';
import Camera from 'react-native-camera';

import ImageResizer from 'react-native-image-resizer';

var cv = require('./computervision');
global.Buffer = global.Buffer || require('buffer').Buffer;
import RNFS from 'react-native-fs';

class testcase2 extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          style={styles.preview}
          aspect={Camera.constants.Aspect.fill}>
          <Text style={styles.capture} onPress={this.takePicture.bind(this)}>[CAPTURE]</Text>
        </Camera>
      </View>
    );
  }

  takePicture() {
    this.camera.capture()
      .then((data) => {
        console.log(data);
        ImageResizer.createResizedImage(data.path, 736, 500, 'JPEG', 25, 0)
        .then((cv_image) => {
          var img = 'file:///' + (cv_image.replace('file:/', ''));

          setTimeout(() => {

            RNFS.readFile(img, 'UTF8')
            .then((file) => {
              console.log(file);
              file = new Buffer(file);
              console.log("Running CV App");
              cv(file);
            })

          }, 2500);

        })
        .catch((err) => {
          if (err) throw err;
        });
      })
      .catch(err => console.error(err));
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  preview: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    height: Dimensions.get('window').height,
    width: Dimensions.get('window').width
  },
  capture: {
    flex: 0,
    backgroundColor: '#fff',
    borderRadius: 5,
    color: '#000',
    padding: 10,
    margin: 40
  }
});

AppRegistry.registerComponent('testcase2', () => testcase2);
```

**Comment by 4ian** [comment]
What's the error? :)

**Comment by ChrisCates** [comment]
@4ian It says "Cannot read file of undefined".

**Comment by 4ian** [comment]
Where is this error coming from? Have you double checked that the file path is correct?

**Comment by ChrisCates** [comment]
@4ian How can I confirm the file path is correct when it's the only file path I get from the react native package o.o...

**Comment by mortik** [comment]
In out Project we need to remove the ```file:``` prefix to make this work on Android. Way are you adding this here? https://github.com/bamlab/react-native-image-resizer/blob/master/android/src/main/java/fr/bamlab/rnimageresizer/ImageResizerModule.java#L55

**Comment by 4ian** [comment]
@mortik If I remember properly, it was to ensure that we can display the image in an Image component. 

>In our Project we need to remove the file: prefix to make this work on Android.

By "make this work on Android", you mean working with `react-native-fs`?

**Comment by mortik** [comment]
yes but react-native-fs only has a problem with the path returned from the image-resizer on android on iOS this works without a problem but that path has no ```file:``` prefix.

**Comment by Okipa** [comment]
I had the same problem. A little note in the documentation would be great about this !
I have been googling for hours before finding this solution, and @mortik seems to confirm that I am not the only one that met this problem ;)

**Comment by amanthegreatone** [comment]
@Okipa @mortik 
can someone clarify whats the filepath supposed to be like?

i have a filepath from react-native-fs like this "/storage/emulated/0/Pictures/RNTest/TST_IMG_20170110_001704.jpg" and it throws an error "open failed: ENOENT (No such file or directory)"

I also tried using the uri that I get from the react-native-camera which is like this "file:///storage/emulated/0/Pictures/RNTest/TST_IMG_20170110_002103.jpg" but again got the same error.


this is the function i am using

```
resize(path, outputPath) {
    console.log("path: " + path, "outputPath: " + outputPath);
     ImageResizer.createResizedImage(path, 800, 600, 'JPEG', 50, 0, outputPath)
     .then((resizedImageUri) => {
       console.log(resizedImageUri);
     }).catch((err) => {
       console.log(err);
     });
   }
```

**Comment by amanthegreatone** [comment]
The path I figured should not have the "file://" as in case of the uri being sent from the react-native-camera but it should be the path from the react-native-fs. 

Having corrected that I was having issues with the outputPath. For some reason it is not giving the resized image for the specified outputPath but a blank uri "file:". I removed the outputPath parameter and then got the resized image in the cache "file:/data/user/0/com.reactnotes/cache/1483994682440.JPEG"

So I get the cached filepath of the resized image and then use react-native-fs to move it to the outputPath I want.

```
const resizedImagePath = resizedImageUri.replace("file:/", "");

RNFS.exists(resizedImagePath).then( (result) => { 
         RNFS.moveFile(resizedImagePath, outputPath)
           .then(() => {
             console.log('RESIZED FILE MOVED');
           })
           .catch((err) => {
             console.log(err.message);
           });
```

Please check if there is an issue with the outputPath parameter or if I am making some mistake which I have been unable to see.

**Comment by Okipa** [comment]
You just should replace your path `file:///storage/emulated/0/Pictures/RNTest/TST_IMG_20170110_002103.jpg` by `//storage/emulated/0/Pictures/RNTest/TST_IMG_20170110_002103.jpg`

You can do something like this :
```
correctPath = originalPath.replace('file:/', '');
```

**Comment by cooperka** [comment]
@Okipa you shouldn't be removing that slash, just `file:`. Using `originalPath.replace('file:', '');` fixes it for me.

@4ian would you like me to submit a PR removing the prefix on Android? I'd be happy to if you don't think it would cause other issues.

**Comment by Okipa** [comment]
You're right, I added the extra "/" by mistake. I update my post to avoid confusion.

**Comment by 4ian** [comment]
Hey guys, thanks for the follow up!
@cooperka A PR would be nice but I'm indeed concerned about the backward compatibility and the fact that the path can't be used directly for `Image` :/ I honestly am not sure about what's better. Being able to quickly to preview the result in an `Image` component is really important as it's easy to use.

**Comment by cooperka** [comment]
@4ian it's tough to know what's better! Maybe like you said, since it's already there, for the sake of backward compatibility we should leave it and instead update the README to explain the need to remove `file:` on Android before using the path with something like `fs`.

**Comment by 4ian** [comment]
@cooperka Sounds good to me, a comment in the README (maybe with a nice ⚠️ emoji :)) could help and do not create a breaking change.

**Comment by Okipa** [comment]
+1 !

**Comment by wmonecke** [comment]
This is reaaally weird. I have been debugging for like 2 hours and being frustrated to why my Image from RNFS.downloadFile wont render on Android but it will on iOS.

If i add `file://` before the path returned by `.downloadFile`  it works on ANDROID and on iOS I just insert the path directly (without `file://`) is this how it should work??

**Comment by guptavishesh143** [comment]
Converting to Base64 Works for Image showing

 ```
const DownloadUrl = async () => {
var RNFS = require("react-native-fs");

RNFS.downloadFile({
  fromUrl: "https://facebook.github.io/react-native/img/header_logo.png",
  toFile: `${RNFS.DocumentDirectoryPath}/react-native.png`,
}).promise.then(async (response: string) => {
  RNFS.readFile(
    `${RNFS.DocumentDirectoryPath}/react-native.png`,
    "base64"
  ).then((base64String: any) => {
    console.log(
      "base64String===>",
      `${RNFS.DocumentDirectoryPath}/react-native.png`,
      base64String
    );
  });
  console.log("response ====>", RNFS.DocumentDirectoryPath, response);
});
```
