### ISSUE TITLE
Question: Any Plans to do this For Video?

### ISSUE THREAD

**Issue by quadsurf** [bamlab/react-native-image-resizer#57]
If you have no plans to extend this to video resizing/compression, do you know of any other RN libraries that do? Google search was not helpful :-(

**Comment by 4ian** [comment]
For now, no plan to extend or create another `react-native-video-resizer` module, as we don't have this use case. Sorry :/

**Comment by binora** [comment]
@quadsurf Hey, did you find anything regarding video compression?
