### ISSUE TITLE
TypeError: undefined is not an object: evaluating ImageResizerAndroid.createResizedImage

### ISSUE THREAD

**Issue by saeed2402** [bamlab/react-native-image-resizer#58]
Hi all,
I get the error above when I select an image. I am using Google Nexus 6 emulator and here's my code snippet:

```
..
import ImageResizer from 'react-native-image-resizer';
..
resize(uri) {
        // source = { uri: response.uri.replace('file://', ''), isStatic: true };
        alert(ImageResizer);
        ImageResizer.createResizedImage(uri, 600, 400, 'JPEG', 80)
            .then((resizedImageUri) => {
                this.setState({
                    isLoadingImage: false,
                    imageSource: { uri: resizedImageUri, isStatic: true }
                });
            }).catch((err) => {
                alert(err)
                return Alert.alert('Unable to resize the photo',
                    'Check the console for full the error message');
            });
    }
```

Thanks for your time in advance.

**Comment by 4ian** [comment]
I've edited your post to add code formatting, please check this guide to see how to do it next time: https://guides.github.com/features/mastering-markdown/ 😉 

The error is related to `ImageResizerAndroid` but I can't see it in your code.
Can you please copy-paste your entire code snippet along with the full stack-trace of the error? Thanks :)

**Comment by saeed2402** [comment]
Thanks for quick response and the tip.
I checked (https://github.com/bamlab/react-native-image-resizer/pull/35/commits/83bb4bbd21e910c51536a0317be1f2f04fae292e)  and I can see my ImageResized.java code matched that. So I assume I am using the latest version of the project.
I am not using ImageResizerAndroid in my code, is it not called when this module is used in Android?

**Comment by 4ian** [comment]
Can you tell me the version of `react-native-image-resizer` that you have in your `package.json`?
Can you copy-paste the entire stack-trace of the error? It will really help me because otherwise I can miss important information.

**Comment by saeed2402** [comment]
"react-native-image-resizer": "0.0.12"
And what do you exactly mean by full trace of error message? Sorry, I'm very new to this kind of programming and React.
The error is what I get from the second alert in my code above.
UPDATE: I ran my app just now again, and now the error is changed to: _`TypeError: Cannot read property 'createResizedImage' of undefined`_

**Comment by saeed2402** [comment]
@4ian Haven't heard back from you buddy, do you need any other info?

**Comment by saeed2402** [comment]
My issue was resolved after I ran the link command once again. Not sure why it worked for ios first time but not for Android.

**Comment by 4ian** [comment]
Sweet! :) Sorry for not being more helpful! The fact that the module was `undefined` should have been a good hint to me that the native module wasn't linked properly.
