### ISSUE TITLE
Getting Execution failed for task ':app:packageAllDebugClassesForMultiDex'. > java.util.zip.ZipException: duplicate entry: android/support/v7/appcompat/R$anim.class while launching my app through command promt

### ISSUE THREAD

**Issue by sibaditya** [bamlab/react-native-image-resizer#63]

**Comment by 4ian** [comment]
What is your version of React Native and your version of the plugin?
Try to do as instructed in the README (https://github.com/bamlab/react-native-image-resizer#android): `cd android && ./gradlew clean` 😉

**Comment by sibaditya** [comment]
@4ian : Thanks a lot. Its working.

**Comment by 4ian** [comment]
Cool! Closing this issue :)
