### ISSUE TITLE
"Can't retrieve the file from the path"

### ISSUE THREAD

**Issue by ghost** [bamlab/react-native-image-resizer#66]
I am unable to input an image path into the resizer, am I missing something? RN version 0.39.2

Here is my code:
ImageResizer.createResizedImage('./img/toast.png', 100, 100, 'PNG', 100).then((resizedImageUri) => {
          this.setState({image: resizedImageUri, loaded: true})
      }).catch((err) => {
          console.log(err)
        });

**Comment by 4ian** [comment]
You should use an absolute path, try getting a file for example with RNFS before passing it to `createResizedImage` :)

**Comment by sebringj** [comment]
This is failing with an absolute path (ios/react 58)
