### ISSUE TITLE
v0.1 not working with react native 0.41

### ISSUE THREAD

**Issue by forki** [bamlab/react-native-image-resizer#68]
It seems v0.1 is not working with react native 0.41 under android:

![v1](https://cloud.githubusercontent.com/assets/57396/22976858/ba43d208-f38c-11e6-8e3f-b543833b453a.png)

![v2](https://cloud.githubusercontent.com/assets/57396/22976864/beac3786-f38c-11e6-9b76-4c814aa2dd75.png)

**Comment by 4ian** [comment]
I never tried it on Windows (and never tried React Native on Windows too). Was it working in a previous release?

**Comment by forki** [comment]
Yes. Downgrade works.

**Comment by PierreCapo** [comment]
Closed as staled issue with old version of React-Native or react-native-image-resizer.
