### ISSUE TITLE
Error resizing base64 image

### ISSUE THREAD

**Issue by passabilities** [bamlab/react-native-image-resizer#69]
`image` is defined and a valid base64 image data.
```
        ImageResizer.createResizedImage(`data:image/jpeg${image}`, 800, 600, 'JPEG', 80).then( uri => {
        }).catch( err => Alert.alert(JSON.stringify(err)))
```

When I run this, it retuns returns no useful information telling me what went wrong:
```
{"line":85298,"column":40,"sourceURL":"http://192.168.0.12:8081/imdex.ios.bundle?platform=ios&dev=true&hot=true"}
```

**react-natvie**: 0.24.1
**react-native-image-resizer**: 0.0.12

**Comment by ChristianTucker** [comment]
Try `'data:image/jpeg;base64,'+image`

**Comment by passabilities** [comment]
I've tried that as well 😕 
I believe the root issue is with #71

**Comment by developercode1** [comment]
Did anyone find solution for this? I am facing this problem. The error says bad base-64 .

**Comment by Kicker93** [comment]
This works: 'data:image/jpeg,'+image
The code expects a comma before the base64 image, for some reason...
