### ISSUE TITLE
Resize Image Without Preserving Pixel Ratio

### ISSUE THREAD

**Issue by Burak07** [bamlab/react-native-image-resizer#70]
First of all thank you for component. It works as expected.

I wonder if it is possible to resize image withour preserving pixel ratio. Assume that I want to keep my all images 200x200.

**Comment by 4ian** [comment]
Hey @Burak07! This is not possible for now, the given width/height are always used as a maximum size, the resizing being done to keep aspect ratio.
If you have some time, you could add an optional `keepAspectRatio` parameter (being true by default) and if set to false, change the function doing the resize in the Java and Objective-C code. 😄

**Comment by LRNZ09** [comment]
Related issue https://github.com/bamlab/react-native-image-resizer/issues/33
