### ISSUE TITLE
No visible @interface for 'RCTImageLoader' declares the selector loadImageWithURLRequest:callback:'

### ISSUE THREAD

**Issue by passabilities** [bamlab/react-native-image-resizer#71]
using react-native 0.24.1

using react-native-image-resizer v. 0.0.12 like the README says

**Comment by 4ian** [comment]
Looks like you're using a version of React Native that do not have `loadImageWithURLRequest` method but `loadImageWithTag` which was deprecated and then removed from React Native. See this commit for the change that we had to make: https://github.com/bamlab/react-native-image-resizer/commit/8e9adf7a13d676e781e964c81c14a9d345847d9d

I did a breaking change note here: https://github.com/bamlab/react-native-image-resizer/releases/tag/0.0.9 but it's not in the README, so I'm going to update it.
You can try to use version 0.0.8 of the module which should be compatible with RN 0.24.1, but I strongly advise you to upgrade RN instead. I think it's getting dangerous to be using such an outdated version of React Native, and an outdated version of the module 😉 

Upgrade is a bit time consuming but you should be able to do it by doing progressive upgrades between version of React Native with breaking changes. Be sure to test the whole app at each upgrade and apply any fix/codemod related to the upgrade of React Native.

**Comment by 4ian** [comment]
README updated: https://github.com/bamlab/react-native-image-resizer/commit/d568ed104a7f71d5d342d129894748d62251b2a9 :)

**Comment by passabilities** [comment]
Thank you so much! I'll give it a try now. But yes I agree React Native needs to be upgraded but I'm working on a side project that is using this version and would cause an even bigger headache to upgrade.. I've strongly advised that be the course of action but the client didn't have it in the budget or time to.

**Comment by PierreCapo** [comment]
Closed as staled issue with old version of React-Native or react-native-image-resizer.
