### ISSUE TITLE
Tmp file is named with jpg extension for both jpg and png

### ISSUE THREAD

**Issue by fantapop** [bamlab/react-native-image-resizer#72]
I was confused about this briefly, since i specified PNG type.  It looks like this line is assuming the tmp file with be a jpeg:

https://github.com/bamlab/react-native-image-resizer/blob/master/ios/RCTImageResizer/RCTImageResizer.m#L97

**Comment by fantapop** [comment]
This does not repro on android fwiw

**Comment by 4ian** [comment]
The android module is indeed properly handling the output file extension (https://github.com/bamlab/react-native-image-resizer/blob/master/android/src/main/java/fr/bamlab/rnimageresizer/ImageResizerModule.java#L47) but the iOS has "jpg" extension hardcoded.
I guess the first step to avoid confusion would be to remove this extension, or better have an extension adapted to the `format` (https://github.com/bamlab/react-native-image-resizer/blob/master/ios/RCTImageResizer/RCTImageResizer.m#L90)

**Comment by 4ian** [comment]
Should be fixed by #90 :) Thanks @Uby501!
