### ISSUE TITLE
Cannot read property 'createResizedImage' of undefined

### ISSUE THREAD

**Issue by webmafia7** [bamlab/react-native-image-resizer#73]
Hi Guys,

I'm using react ~15.4.2 and react-native 0.42.0 and am getting this error when I try to use the resizeImages in Android. Works fine in iOS. I have install node modules, run rnpm link and everything seems to link fine. Do you have instructions on how I can link this manually?

Thanks

**Comment by 4ian** [comment]
Can you post the result of the `react-native link` command? And the diff that is generated? A few files should be updated in the `android` folder to add the image resizer package.

**Comment by webmafia7** [comment]
rnpm-link info Linking react-native-image-resizer android dependency 
rnpm-link info Android module react-native-image-resizer has been successfully linked 
rnpm-link info Linking react-native-image-resizer ios dependency 
rnpm-link info iOS module react-native-image-resizer has been successfully linked

**Comment by webmafia7** [comment]
After linking, the only file that changes is the project.pbxproj file which contains information about the libRCTImageResizer.a file. Np changes appear in the android folder.

**Comment by 4ian** [comment]
That's not normal for sure. I've tried on a blank react native project and looks like it's working properly. I've done:
```
react-native init TempTestResizer && cd TempTestResizer
git init .
git add -A
git ci -m "Initial commit"
npm install --save react-native-image-resizer
react-native link react-native-image-resizer
git diff > diff.txt
```

Here is the result:
[diff.txt](https://github.com/bamlab/react-native-image-resizer/files/846176/diff.txt)

In particular, android/app/build.gradle, android/app/src/main/java/com/temptestresizer/MainApplication.java and android/settings.gradle have been updated to include, compile and add the package. 

You can take a look at the diff if you want to try to add these 3 changes by yourself. But it's strange that react-native link is failing silently. Have you manually modified these files?

**Comment by webmafia7** [comment]
Many thanks let me try this. Yep I agree when I looked at the android folder it was clear the linking was not updating the required files.

**Comment by webmafia7** [comment]
Ok unlinked the library, ensured everything had been removed from the android folder and re-linked using your command and it worked, maybe an issue with rnpm link. Sorry to bother and many thanks for your help.

**Comment by 4ian** [comment]
Sweet 👍
