### ISSUE TITLE
Published version is out of date (0.1.0)

### ISSUE THREAD

**Issue by cooperka** [bamlab/react-native-image-resizer#74]
Please publish the latest code to npm :) The [current version](https://www.npmjs.com/package/react-native-image-resizer) is v0.1.0 which is over 2 months old and doesn't include several changes. Thanks.

**Comment by jkimbo** [comment]
+1 on this! I would have just installed it from npm if I hadn't seen this issue.

**Comment by WandersonAlves** [comment]
one year later, and zero updates
![image](https://user-images.githubusercontent.com/9141449/52730349-e3cee680-2f99-11e9-8c5c-136bcc2c5ffc.png)

**Comment by Minishlink** [comment]
Sorry guys for the delay, I was lacking rights on publishing this package. It's released as `v1.0.1`.
