### ISSUE TITLE
can no longer load images from http:// urls on android

### ISSUE THREAD

**Issue by npomfret** [bamlab/react-native-image-resizer#75]
I used to be able to load images from the web directly into this module, and I still can on iOS.  But it's broken on android. I just get a url back "file:"... which also feels like the error handling has got worse.

I think it may be to do with this commit: https://github.com/bamlab/react-native-image-resizer/commit/8a485bf0a9694fadaaa5aa355cb0c31da448c416

**Comment by m191007** [comment]
android cannot load the path

**Comment by brunolemos** [comment]
I'm facing a uncatch error and I think it's related to this.
