### ISSUE TITLE
outputPath should include filename

### ISSUE THREAD

**Issue by wandonye** [bamlab/react-native-image-resizer#77]
Currently there isn't a way to set the filename of the resized image.
I know I can do a rename afterward, but it would be cleaner to set the target image name within the API

**Comment by alainib** [comment]
can you past an exemple for the outputPath please ?

i don't know how to initialise it. all folder i put i get `open failed: ENOENT (No such file or directory)`

**Comment by Faolain** [comment]
@4ian is this something that can be done or is there a reason why this is currently not supported?
