### ISSUE TITLE
TypeError: Cannot read property 'createResizedImage' of undefined

### ISSUE THREAD

**Issue by xyy7260** [bamlab/react-native-image-resizer#82]
Thank the authors for providing such a good component
 I am according to your document installed for use, call the method that you use in the console back to # # 
TypeError: always read the property 'createResizedImage of undefined   

**  let  url = this.state.compressionImg ;
            // let data = this.state.compressionData;
        ImageResizer.createResizedImage(url, 100, 100, 'JPEG', 25, 0).then((resizedImageUri) => {
            console.log(resizedImageUri)
        }).catch((err) => {
            console.log(err);
        });
**

**Comment by 4ian** [comment]
Could you provide me with:
* The full source code of the file where you're using ImageResizer?
* The OS (iOS or Android) that you're testing your app on,
* Which version of React Native are you using and which version of this package? (you can find that in your `package.json`)

Did your run `react-native link`? Can you paste the output of this command if you launch it again?

**Comment by xyy7260** [comment]
- The react - native image-resizer version is 0.1.1
- It's android
- My "react - native" : "0.43.3", "react" : "16.0.0-alpha."
- When I'm done, I'm on link

**Comment by xyy7260** [comment]
- This is the component code that I wrote
[https://github.com/xyy7260/Image-compression-error](url)
@4ian  thank you

**Comment by xyy7260** [comment]
This is my code
[https://github.com/xyy7260/Image-compression-error](url)
@4ian    thank you

**Comment by xyy7260** [comment]
This is my code
 [https://github.com/bamlab/react-native-image-resizer/issues/82](url)
@4ian thank you

**Comment by xyy7260** [comment]
[This is my code](https://github.com/xyy7260/Image-compression-error)
@4ian thank you

**Comment by xyy7260** [comment]
## Image-compression-error
 -----------------------------------------------------
 * The react - native image-resizer version is 0.1.1
 * It's android
 * My "react - native" : "0.43.3", "react" : "16.0.0-alpha." 
---------------------------------------------------------
 ###### The code of the component  

     import React, { Component } from 'react';
     import {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    TouchableOpacity,
    Image,
    TextInput,
    Dimensions,
    Alert,
    Platform
     } from 'react-native';
     const { width } = Dimensions.get('window');
     const {height } = Dimensions.get('window');


     import ImagePicker from 'react-native-image-picker';  
     import ModalDropdown from 'react-native-modal-dropdown';   
     import ImageResizer from 'react-native-image-resizer';
     import Http from '../http';

     let headHeight = 150;
 
     let headImageHeight = 120;
 
     let cellHeight = 50;

     const photoOptions ={
     //底部弹出框选项
     title: '选择图片',      
     cancelButtonTitle:'取消', 
     takePhotoButtonTitle:'相机', 
     chooseFromLibraryButtonTitle:'从相册选择', 
     quality: 0.7, // 
     maxWidth: headHeight, 
     maxHeight: headImageHeight,
     storageOptions: {
         skipBackup: true,  
         cameraRoll:true,  
          //allowsEditing: true, 
          path: 'images',
          }
      };
     class ModalExample extends Component {
         constructor(props) {
        super(props);
        this.state = {
            headImages :  null,    
            agentImages : null,   
            compressionImg : null ,  
            compressionData:null,  
   
             };
         }
     cameraAction(){
        ImagePicker.showImagePicker(photoOptions, (response) => {
            console.log('Response = ', response);

            if(response.didCancel) {
                console.log('User cancelled image picker');
                console.log("用户取消选择器")
            }
            else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
                Alert.alert('提示','您未开启访问相册的权限,请在"设置"中打开该权限');
            }
            else if (response.customButton) {
                console.log('User tapped custom button: ', response.customButton);
                console.log("自定义按钮")
            }
            else {
                let imgdata = response.data;    
                let uri = Platform.OS === 'ios' ? response.uri.replace('file://', '') : response.uri;
                let fileName = uri.split('/').pop();
                let source;   
                source = {uri: 'data:image/jpeg;base64,' + response.data};
                if (Platform.OS === 'android') {
                    source = { uri: response.uri };
                } else {
                    source = { uri: response.uri.replace('file://','') };
                }
               this.setState({
                   headImages : source,
                   compressionImg: uri,       // The picture     
                   compressionData:imgdata

               });
               //console.log(imgdata);
               // console.log(uri);
                //console.log(fileName);
            }
        });
    }
    
###### This is the component of image compression
    submitAll(){
        let  url = this.state.compressionImg ;
            // let data = this.state.compressionData;
        ImageResizer.createResizedImage(url, 100, 100, 'JPEG', 25, 0).then((resizedImageUri) => {
            console.log(resizedImageUri)
        }).catch((err) => {
            console.log(err);

        });
    }
  
    render() {
        return (
          <View style={styles.body}>
               <View style={styles.topX}>
                   <TouchableOpacity
                    onPress={this._fhworde.bind(this)}
                   >
                       <Image
                        source={require('../img/registered_icon/X.png')}
                        style={styles.imgStyle}
                       />
                   </TouchableOpacity>
                   <TouchableOpacity>
                      <Text style={styles.fontright}>
                          登录
                      </Text>
                   </TouchableOpacity>
               </View>
               {/*省市*/}
              <View style={styles.topstyle}>
                  <ModalDropdown
                      defaultValue="所属省"
                      options={this.state.andwords}
                      dropdownStyle={styles.fontStyles}
                      textStyle={styles.fontcolorstyle}
                      style={styles.anfontStyles}
                      onSelect={(index,value)=>{this.wordname(index,value)}}
                  />
                  <Image
                   source={require('../img/registered_icon/v.png')}
                   style={styles.Vstyles}
                  />
              </View>
               
              </View>
              {/*营业执照和代理商*/}
              <View style={styles.angtnName}>
                  <TouchableOpacity
                      onPress={()=>{this.cameraAction()}}
                  >
                  <View style={styles.angtnimgLeft}>

                      { this.state.headImages === null ?  <Image style={styles.topimg} source={require('../img/registered_icon/iiiiii.png')}/> :
                          <Image
                              // style={styles.topimg}
                              source={this.state.headImages}
                              style={styles.headImage}
                          />
                      }
                  </View>
                  </TouchableOpacity>

                  <TouchableOpacity
                      onPress={()=>{this.cameraActions()}}
                  >
                      <View style={styles.angtnimgRight}>

                          { this.state.agentImages === null ?  <Image style={styles.topimg} source={require('../img/registered_icon/iiiiii.png')}/> :
                              <Image
                                  // style={styles.topimg}
                                  source={this.state.agentImages}
                                  style={styles.headImage}
                              />
                          }
                      </View>
                  </TouchableOpacity>

              </View>
              {/*上传获取的值*/}
              <View style={styles.ViewgoComplete}>
              <TouchableOpacity
                  activeOpacity={0.6}
                  onPress={()=>{this.submitAll()}}
              >
              <View style={styles.goComplete}>
                  <Text style={styles.goCompletesize}>完成</Text>
              </View>
              </TouchableOpacity>
              </View>

          </View>
        );
    }
    _fhworde(){
        const {navigator} = this.props;
        if (navigator){
            navigator.pop()
        }
    }
    //省
    wordname(index,value){
        let  ProvincesVlue  = value;   //选中的名字
        let ProvincesCode = this.state.provinceCode[index];  //选中过后的code
       this.setState({
           province : ProvincesVlue,
           selectprovinceCode : ProvincesCode
       });
       this.cityNmae(ProvincesCode);
    }
   
    //代理选择
    agent(index,value){}
    //加载阶段
    componentDidMount(){
        this.Provinces(); //获取省信息
        this.agentBusiness()
    }
   
     export default ModalExample;  //es6

**Comment by xyy7260** [comment]
-  Error in the console. Log print
![rz1yzg4s8 us2 y2kxg jfa](https://cloud.githubusercontent.com/assets/23183393/26753432/88c7e5dc-4898-11e7-9781-d4b8e1e64e48.png)

**Comment by xyy7260** [comment]
@4ian

**Comment by Jasonvdb** [comment]
I had the same issue, then saw I forgot to run recompile my app through xcode and android studio after running the link command. Maybe try a clean recompile?

**Comment by holyxiaoxin** [comment]
I did a new recompile using react-native link and it fixed the issue.

**Comment by katlavan** [comment]
Also if you still receive such errors please recheck linking diff from file in the comment - https://github.com/bamlab/react-native-image-resizer/issues/73#issuecomment-286902162
MainApplication.java was without package importing - so linking doesn't work properly.

**Comment by mtreerungroj** [comment]
I just had the same issue for Android. I used `react-native link` after installing `react-native-image-resizer` but it's not working.

To fix it, I do manual linking
in `android/app/build.gradle` add
```
dependencies {
    ...
    compile project(':react-native-image-resizer')    
    ...
}
```

in `MainApplication.java` add
```
import fr.bamlab.rnimageresizer.ImageResizerPackage;

...

@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new ImageResizerPackage() // <------ Add this line
      );
}
```

and in ` android/settings.gradle` add
```
include ':react-native-image-resizer'
project(':react-native-image-resizer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-resizer/android')
```

Noted that I use:
`react-native` : 0.47.0
`react-native-image-resizer` : ^1.0.0

**Comment by augustolazaro** [comment]
You have to rebuild the app after install a native library. Just re-run `react-native run-ios` (or Android) and you will get it working.

**Comment by ankit7878** [comment]
Removing Build from iOS did the job.. thnx
i followed this 2 below step and it solved the issue:
1. run command `react-native link`
2. remove build directory from iOS and rebuild

**Comment by Stas-Buzunko** [comment]
had the same problem, had to link manually
https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by JuanDeLeon** [comment]
I'm having the same problem for IOS, already uninstalled/unlinked react-native-image-resizer, and then reinstalled again linking manually and also with link CLI, no luck.
Using "react": "16.2.0", and "react-native": "^0.52.2",

TypeError: Cannot read property 'createResizedImage' of undefined
    at MessageScreen.js:2
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at Object.createResizedImage (zooming-exits.js:46)
    at HomeScreen.resizePicture (HomeScreen.js:84)
    at HomeScreen.proxiedMethod (createPrototypeProxy.js:44)
    at Object.touchableHandlePress (TouchableOpacity.js:199)
    at Object._performSideEffectsForTransition (Touchable.js:746)
    at Object._receiveSignal (Touchable.js:664)

**Comment by JuanDeLeon** [comment]
Got it working after a few times. Last time I used CLI link, then rebuilt and ran in Xcode and directly into my phone.

**Comment by jcgh582** [comment]
Same error. This could be the worst npm module I have ever used.

**Comment by 4ian** [comment]
Criticizing the hours of work that have been put in making this module won't help 🤨All of this is done on the spare time of contributors and maintainers. 
Please refrain to be so hard and propose your help instead if something is missing or broken. 
Thanks!

**Comment by DIGITALSQUAD** [comment]
I'm using [CocoaPods](https://cocoapods.org/) and `pod install` in ios directory fixed the error.

**Comment by zhuhengtan** [comment]
drag the project into libraries and add libRCTImageResizer.a to Link Binary With Libraries, then re-run the project, done.

**Comment by PierreCapo** [comment]
Closed as staled issue with old version of React-Native or react-native-image-resizer.
