### ISSUE TITLE
Unable to load source image from path

### ISSUE THREAD

**Issue by m191007** [bamlab/react-native-image-resizer#84]
on android platfrom 
Unable to load source image from path

**Comment by daominhsangvn** [comment]
I got this issue too.

**Comment by 4ian** [comment]
Can you post the full stackstrace of the error?
Can you also `console.log` the path of the image?

**Comment by daominhsangvn** [comment]
I have fixed this, i got this error because i pass the file path which is lead to nothing.

**Comment by tikkichan4** [comment]
Same problem. But i am sure that i passed the current image uri to the createResizedImage(...)

**Comment by RagamAnekaGlobal** [comment]
same probem, works in ios and not works in android

**Comment by zahid313** [comment]
same issue. Image is present. Other images in same path have been uploaded but not this particular image

**Comment by almasaeed2010** [comment]
I am experiencing the same issue with v1.0.0 on Android although `adb shell` shows that the path exists:
```shell
# Error From Log
'Unable to load source image from path'
# Path passed to function call
'/data/user/0/com.awesomeapp/files/images/8gvGS59fc8a6d33dfa.jpeg'
```

Function call:
```js
let image = '/data/user/0/com.awesomeapp/files/images/8gvGS59fc8a6d33dfa.jpeg'
ImageResizer.createResizedImage(image, 160, 160, 'JPEG', 100, 0, this._thumbnailsDir)
.then(({uri}) => {
        //
})
.catch((error) => {
        console.log('Unable to create thumbnail: ', error, image)
})
```
The function works perfectly on iOS.

Any help is appreciated. Thanks!

**Comment by daominhsangvn** [comment]
For the android, you must use base64 then use RNFS to create new image based on the base64.

**Comment by daominhsangvn** [comment]
Try this:
```
response = async (result) => {
   let path = result.uri || result.path;
      if (Platform.OS === 'android') {
        let newFilePath = `${RNFetchBlob.fs.dirs.CacheDir}/${path.substring(path.lastIndexOf('/') + 1)}`;
        let newFile = await RNFetchBlob.fs.writeFile(`${RNFetchBlob.fs.dirs.CacheDir}/${path.substring(path.lastIndexOf('/') + 1)}`,
          result.base64,
          'base64');
        path = newFilePath;
      }

      if (/^\/private/.test(path)) {
        path = path.substring(8);
      }
      if (!/^file:/.test(path)) {
        path = `file://${path}`;
      }

      return {
        height: result.height,
        width: result.width,
        isVertical: true,
        cancelled: false,
        uri: path,
        fileSize: result.size,
        mime: result.mime,
        data: result.data
      };
  };

  action = async (type) => {
    let result;
    let options = {
      cropping: true,
      allowsEditing: true,
      aspect: [1, 1],
      base64: Platform.OS === 'android'
    };

    switch (type) {
      case 1:
        result = await ImagePicker.openCamera(options);
        break;
      case 2:
        result = await ImagePicker.openPicker(options);
        break;
    }

    if (result && !result.cancelled) {
      return await this.response(result);
    }
    return null;
  };
```

**Comment by Gopalakrishnan-V** [comment]
Getting the same error in android: Unable to load source image from path
Any update on this? @PierreCapo @robertbarclay @JimTeva

**Comment by apgsn** [comment]
It could be a scoped storage issue. I solved it by adding:`android:requestLegacyExternalStorage="true"` to my AndroidManifest, inside the `application` tag.
Note that this is a [temporary workaround](https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage).

**Comment by mikekudzin** [comment]
This error also could be thrown if an error exist in data schema. In my case I had to fix  "Unable to load source image from path" Android while iOS was working perfectly. The cause was misspelling:  `data:image/jpg;base64,${base64Image}` was used instead of `data:image/jpeg;base64,${base64Image}` (note jpg vs jpeg). Plugin's native android part requires strict scheme while iOS not.
