### ISSUE TITLE
Uri Err

### ISSUE THREAD

**Issue by sdqyang** [bamlab/react-native-image-resizer#9]
I used your program code , but Andrews in dealing uri of an error , I read you have modified , can you publish it?

**Comment by 4ian** [comment]
Sorry `npm publish` was giving me 503 errors yesterday. This should be published now: version 0.0.3 should be up-to-date with the latest commits on master, fixing several things. :)

Let me know if it's ok and I'll close the issue.

**Comment by sdqyang** [comment]
谢谢你~！thank you!
