### ISSUE TITLE
can not resize image to png

### ISSUE THREAD

**Issue by leogeng** [bamlab/react-native-image-resizer#91]
I  want to resize png file, and implement the code as the following.
ImageResizer.createResizedImage(inputPath, width, height, "PNG", 80, 0, path)

But the result is that I got a jpg image.

**Comment by 4ian** [comment]
On which platform are you having the issue?
Probably a issue with filenaming that has been solved recently: https://github.com/bamlab/react-native-image-resizer/issues/72
So the image is actually a PNG file but named with a JPG extension. This will be fixed in the next release! :)

**Comment by 4ian** [comment]
New version is released and issue should be fixed, I'm closing the issue :) Let me know if there is still any problem.
