### ISSUE TITLE
Response only returns the path 

### ISSUE THREAD

**Issue by AlmogRnD** [bamlab/react-native-image-resizer#95]
So response only returns the path 
for example "/Users/Almog/Library/Developer/CoreSimulator/Devices/60FE8A5A-9C39-4A10-8171-0CAD10F64947/data/Containers/Data/Application/77125FFF-72D6-44C1-975A-D205BE3C7038/Library/Caches/5CF9B6F6-4E8F-4A07-8F1D-C3D7AE6897D1.jpg" 

In the example you have the following 

 // response.uri is the URI of the new image that can now be displayed, uploaded...
  // response.path is the path of the new image
  // response.name is the name of the new image with the extension
  // response.size is the size of the new image 

But none of them work, they all return undefined

**Comment by 4ian** [comment]
The upcoming version on branch master is not released yet but the response changed to have more information (both on iOS and Android). In the version you have, only the path was returned.
You can stick with this for now and wait for the new version release (it's a breaking change, so major version number will be increased) or use the module from master branch.

**Comment by pankaj-ag** [comment]
Is there any update on this one

**Comment by 4ian** [comment]
I've just published version 1.0.0 with the new interface and up-to-date typescript and flow type definitions 😄 
I'm closing the issue as it should works properly, let me know if you have any problem.
